/* Sunshine English · Grade 8 — original classroom content */
(function (root, factory) {
  const data = factory();
  if (typeof module === "object" && module.exports) module.exports = data;
  root.TEXTBOOK = data;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  return {
    meta: {
      title: "Sunshine English",
      titleZh: "阳光英语",
      grade: "八年级",
      gradeShort: "初二",
      volume: "全一册",
      series: "初中英语互动课本",
      storageKey: "sunshine-english-g8",
      mascot: "Pip",
      mascotZh: "小狐皮普",
      blurb:
        "给初中二年级同学的互动英语课本。跟着皮普用过去时讲假期，用比较级聊朋友，再用现在完成时写下自己的故事。",
      homeBookDesc: "打开阳光英语封面，从假期过去时读到现在完成时。",
      homeUnitsDesc: "假期、频率、比较、最高级、节目、打算、未来、制作、健康、请求、过去进行、完成时。",
      tocLede: "十二个单元，跟着皮普从“你去哪儿度假了”走到“你去过博物馆吗”。点进一课就可以听、读、练。",
      diplomaTitle: "阳光英语八年级结业卡",
      diplomaBody: "你读完了十二个单元，会用过去时、将来时和现在完成时讲自己的故事。Pip is proud of you!",
      helloLines: [
        { en: "Hello, world!", zh: "你好，世界！" },
        { en: "How's it going?", zh: "最近怎么样？" },
        { en: "Long time no see.", zh: "好久不见。" },
        { en: "What's new?", zh: "有什么新鲜事？" },
        { en: "Nice to meet you.", zh: "很高兴见到你。" },
      ],
      cast: [
        { en: "Lily", zh: "莉莉" },
        { en: "Tom", zh: "汤姆" },
        { en: "Maya", zh: "玛雅" },
        { en: "Ben", zh: "本" },
        { en: "Ms. Green", zh: "格林老师" },
        { en: "Pip", zh: "皮普" },
      ],
    },

    letters: [
      { letter: "A", word: "adventure", zh: "冒险", emoji: "🧭", ipa: "/æ/" },
      { letter: "B", word: "bridge", zh: "桥", emoji: "🌉", ipa: "/b/" },
      { letter: "C", word: "computer", zh: "电脑", emoji: "💻", ipa: "/k/" },
      { letter: "D", word: "diary", zh: "日记", emoji: "📔", ipa: "/d/" },
      { letter: "E", word: "engineer", zh: "工程师", emoji: "🛠️", ipa: "/e/" },
      { letter: "F", word: "festival", zh: "节日", emoji: "🎉", ipa: "/f/" },
      { letter: "G", word: "goal", zh: "目标", emoji: "🥅", ipa: "/g/" },
      { letter: "H", word: "homework", zh: "作业", emoji: "📚", ipa: "/h/" },
      { letter: "I", word: "idea", zh: "想法", emoji: "💡", ipa: "/aɪ/" },
      { letter: "J", word: "journalist", zh: "记者", emoji: "📰", ipa: "/dʒ/" },
      { letter: "K", word: "kitchen", zh: "厨房", emoji: "🍳", ipa: "/k/" },
      { letter: "L", word: "library", zh: "图书馆", emoji: "📖", ipa: "/l/" },
      { letter: "M", word: "museum", zh: "博物馆", emoji: "🏛️", ipa: "/m/" },
      { letter: "N", word: "notebook", zh: "笔记本", emoji: "📓", ipa: "/n/" },
      { letter: "O", word: "ocean", zh: "海洋", emoji: "🌊", ipa: "/əʊ/" },
      { letter: "P", word: "planet", zh: "行星", emoji: "🪐", ipa: "/p/" },
      { letter: "Q", word: "question", zh: "问题", emoji: "❓", ipa: "/kw/" },
      { letter: "R", word: "robot", zh: "机器人", emoji: "🤖", ipa: "/r/" },
      { letter: "S", word: "science", zh: "科学", emoji: "🔬", ipa: "/s/" },
      { letter: "T", word: "talent", zh: "才能", emoji: "🎭", ipa: "/t/" },
      { letter: "U", word: "umbrella", zh: "雨伞", emoji: "☂️", ipa: "/ʌ/" },
      { letter: "V", word: "vacation", zh: "假期", emoji: "🧳", ipa: "/v/" },
      { letter: "W", word: "weekend", zh: "周末", emoji: "🗓️", ipa: "/w/" },
      { letter: "X", word: "x-ray", zh: "X 光", emoji: "🩻", ipa: "/eks/" },
      { letter: "Y", word: "yogurt", zh: "酸奶", emoji: "🥛", ipa: "/j/" },
      { letter: "Z", word: "zero", zh: "零", emoji: "0️⃣", ipa: "/z/" },
    ],

    units: [
      {
        id: 1,
        title: "Where Did You Go?",
        titleZh: "你去哪儿了？",
        theme: "vacation",
        color: "#3d7ec9",
        emoji: "🧳",
        goals: [
          "用一般过去时谈论假期",
          "问答：Where did you go? What did you do?",
          "读一篇海边旅行的短文",
        ],
        dialogue: {
          title: "Back to School",
          titleZh: "开学第一天",
          scene: "Monday morning. Class 8 meets again after the summer holiday.",
          sceneZh: "星期一早上，八班同学过完暑假又见面了。",
          lines: [
            { speaker: "Ms. Green", text: "Welcome back! Where did you go on vacation, Lily?", zh: "欢迎回来！莉莉，你假期去哪儿了？" },
            { speaker: "Lily", text: "I went to Qingdao with my family. We stayed by the sea.", zh: "我和家人去了青岛。我们住在海边。" },
            { speaker: "Tom", text: "Did you swim every day?", zh: "你每天都游泳吗？" },
            { speaker: "Lily", text: "Almost. The water was a little cold, but it was wonderful.", zh: "差不多。水有点凉，但非常棒。" },
            { speaker: "Maya", text: "I didn't go far. I visited my grandma in the countryside.", zh: "我没走远。我去乡下看望了奶奶。" },
            { speaker: "Ben", text: "I stayed at home and read. It was boring at first, then I liked it.", zh: "我待在家里读书。一开始很无聊，后来我喜欢上了。" },
            { speaker: "Pip", text: "I hid in a suitcase. Nobody found me until the train!", zh: "我藏进了行李箱。直到上火车才有人发现我！" },
            { speaker: "Ms. Green", text: "Write three sentences about your vacation. Use the past tense.", zh: "用过去时写三句关于假期的话。" },
          ],
        },
        vocab: [
          { en: "vacation", ipa: "/vəˈkeɪʃn/", zh: "假期", example: "Where did you go on vacation?", exampleZh: "你假期去哪儿了？" },
          { en: "countryside", ipa: "/ˈkʌntrisaɪd/", zh: "乡下；农村", example: "Maya visited her grandma in the countryside.", exampleZh: "玛雅去乡下看望了奶奶。" },
          { en: "wonderful", ipa: "/ˈwʌndəfl/", zh: "极好的", example: "The sea was wonderful.", exampleZh: "大海美极了。" },
          { en: "bored", ipa: "/bɔːd/", zh: "感到无聊的", example: "Ben was bored at first.", exampleZh: "本一开始觉得无聊。" },
          { en: "stay", ipa: "/steɪ/", zh: "停留；住", example: "We stayed by the sea for a week.", exampleZh: "我们在海边住了一周。" },
          { en: "visit", ipa: "/ˈvɪzɪt/", zh: "拜访；参观", example: "They visited a small museum.", exampleZh: "他们参观了一座小博物馆。" },
          { en: "delicious", ipa: "/dɪˈlɪʃəs/", zh: "美味的", example: "The seafood was delicious.", exampleZh: "海鲜很好吃。" },
          { en: "anyone", ipa: "/ˈeniwʌn/", zh: "任何人", example: "Did anyone go to the mountains?", exampleZh: "有人去山里了吗？" },
        ],
        grammar: {
          title: "Where did you go?",
          titleZh: "一般过去时：询问过去的经历",
          pattern: "Where / What / Did + 主语 + 动词原形? — I went / stayed / didn't go ...",
          notes: [
            "过去时问句用 did，后面动词用原形：Did you swim? 不是 Did you swam?",
            "不规则动词要记：go → went, stay → stayed, read → read。",
            "否定：I didn't go far. 主语后加 didn't，动词回原形。",
          ],
          examples: [
            { en: "Where did you go on vacation? — I went to Qingdao.", zh: "你假期去哪儿了？——我去了青岛。" },
            { en: "Did you swim every day? — Almost. The water was cold.", zh: "你每天都游泳吗？——差不多。水有点凉。" },
            { en: "I didn't go far. I visited my grandma.", zh: "我没走远。我去看望了奶奶。" },
          ],
        },
        reading: {
          title: "A Week by the Sea",
          titleZh: "海边的一周",
          text: "Lily went to Qingdao last August. The family stayed in a small hotel by the sea. On the first morning they walked on the beach. The wind was strong, but the sky was clear.\n\nThey ate delicious seafood in the evening. Lily's dad took many photos. Her mum said the trip was not cheap, but it was wonderful.\n\nOne afternoon they visited a museum about ships. Lily wrote in her diary: \"I didn't feel bored for a minute.\"\n\nOn the train home, Pip climbed out of the suitcase. \"Next vacation,\" he said, \"please buy a ticket for me too.\"",
          textZh:
            "去年八月，莉莉去了青岛。全家人住在海边的一家小旅馆。第一天早上，他们在沙滩上散步。风很大，但天空很晴朗。\n\n晚上他们吃了美味的海鲜。莉莉的爸爸拍了很多照片。妈妈说这趟旅行不便宜，但非常棒。\n\n一天下午，他们参观了一座关于船的博物馆。莉莉在日记里写道：“我一分钟都没有觉得无聊。”\n\n回家的火车上，皮普从行李箱里爬出来。“下次度假，”他说，“也请给我买一张票。”",
        },
        practice: [
          { type: "choice", q: "Where did Lily go on vacation?", options: ["She went to Qingdao.", "She stayed in the countryside.", "She visited a mountain village."], answer: 0 },
          { type: "choice", q: "Did you swim? 里 swim 用的是：", options: ["过去式", "动词原形", "现在分词"], answer: 1 },
          { type: "fill", q: "I _____ to Qingdao with my family last August.", answer: "went", hint: "go 的过去式" },
          { type: "order", words: ["did", "Where", "you", "go", "?"], answer: "Where did you go?" },
          { type: "tf", q: "Maya went far away to another country.", answer: false },
          { type: "listen", audio: "I went to Qingdao with my family.", options: ["I went to Qingdao with my family.", "I stayed at home and read.", "I visited a mountain in winter."], answer: 0 },
        ],
        fun: {
          title: "Vacation chant",
          titleZh: "假期歌",
          chant: [
            "Where did you go? What did you do?",
            "I went to the sea. The sky was blue.",
            "Did you feel bored? No, not a bit.",
            "Past tense stories — that's how we tell it!",
          ],
        },
      },

      {
        id: 2,
        title: "How Often Do You Exercise?",
        titleZh: "你多久锻炼一次？",
        theme: "habits",
        color: "#2f9e6b",
        emoji: "🏃",
        goals: [
          "用频率副词谈论生活习惯",
          "问答：How often do you ...?",
          "读一篇健康生活调查",
        ],
        dialogue: {
          title: "A Health Survey",
          titleZh: "健康调查",
          scene: "PE class is over. Ms. Green asks about daily habits.",
          sceneZh: "体育课结束了。格林老师询问大家的日常习惯。",
          lines: [
            { speaker: "Ms. Green", text: "How often do you exercise, Tom?", zh: "汤姆，你多久锻炼一次？" },
            { speaker: "Tom", text: "I exercise every day. I run before breakfast.", zh: "我每天锻炼。我早饭前跑步。" },
            { speaker: "Lily", text: "I usually play ping-pong twice a week.", zh: "我通常一周打两次乒乓球。" },
            { speaker: "Ben", text: "I hardly ever exercise. I watch too many shows.", zh: "我几乎不锻炼。我看太多节目了。" },
            { speaker: "Maya", text: "I sometimes help at home. I never eat junk food at night.", zh: "我有时在家帮忙。我晚上从不吃垃圾食品。" },
            { speaker: "Pip", text: "I always sleep. Is that a kind of rest?", zh: "我总是睡觉。那算一种休息吗？" },
            { speaker: "Ms. Green", text: "Rest is good. But you should also move. Let's make a better week.", zh: "休息很好。但你也该活动活动。我们来安排更好的一周。" },
          ],
        },
        vocab: [
          { en: "exercise", ipa: "/ˈeksəsaɪz/", zh: "锻炼", example: "How often do you exercise?", exampleZh: "你多久锻炼一次？" },
          { en: "always", ipa: "/ˈɔːlweɪz/", zh: "总是", example: "Tom always runs before breakfast.", exampleZh: "汤姆总是早饭前跑步。" },
          { en: "usually", ipa: "/ˈjuːʒuəli/", zh: "通常", example: "I usually play ping-pong twice a week.", exampleZh: "我通常一周打两次乒乓球。" },
          { en: "sometimes", ipa: "/ˈsʌmtaɪmz/", zh: "有时", example: "Maya sometimes helps at home.", exampleZh: "玛雅有时在家帮忙。" },
          { en: "hardly ever", ipa: "/ˌhɑːdli ˈevə(r)/", zh: "几乎不", example: "Ben hardly ever exercises.", exampleZh: "本几乎不锻炼。" },
          { en: "never", ipa: "/ˈnevə(r)/", zh: "从不", example: "I never eat junk food at night.", exampleZh: "我晚上从不吃垃圾食品。" },
          { en: "junk food", ipa: "/dʒʌŋk fuːd/", zh: "垃圾食品", example: "Too much junk food is bad for you.", exampleZh: "垃圾食品吃太多对你不好。" },
          { en: "housework", ipa: "/ˈhaʊswɜːk/", zh: "家务", example: "How often do you do housework?", exampleZh: "你多久做一次家务？" },
        ],
        grammar: {
          title: "How often ...?",
          titleZh: "询问频率",
          pattern: "How often do you + 动词? — I + 频率副词 + 动词. / I + 动词 + once / twice a week.",
          notes: [
            "频率从高到低：always → usually → often → sometimes → hardly ever → never。",
            "频率副词常放在 be 动词后、实义动词前：I am always busy. I always run.",
            "次数：once a week, twice a week, three times a month。",
          ],
          examples: [
            { en: "How often do you exercise? — I exercise every day.", zh: "你多久锻炼一次？——我每天锻炼。" },
            { en: "Lily usually plays ping-pong twice a week.", zh: "莉莉通常一周打两次乒乓球。" },
            { en: "Ben hardly ever exercises.", zh: "本几乎不锻炼。" },
          ],
        },
        reading: {
          title: "Our Class Habits",
          titleZh: "我们班的习惯",
          text: "Class 8 did a health survey. Tom exercises every day. Lily usually plays ping-pong twice a week. Maya sometimes does housework, and she never eats junk food at night.\n\nBen's answers were honest. He hardly ever exercises. He always watches shows after dinner. \"I know it is not healthy,\" he said.\n\nMs. Green put the results on the board. \"Good habits are not a race,\" she said. \"Start with three times a week. Walk, play, or help at home.\"\n\nPip wrote: I always rest. Next week I will sometimes jump. Everyone laughed, then they made a plan.",
          textZh:
            "八班做了一次健康调查。汤姆每天锻炼。莉莉通常一周打两次乒乓球。玛雅有时做家务，晚上从不吃垃圾食品。\n\n本的回答很诚实。他几乎不锻炼。晚饭后他总是看节目。“我知道这不健康，”他说。\n\n格林老师把结果写在黑板上。“好习惯不是比赛，”她说，“先从一周三次开始。走路、玩耍，或在家帮忙。”\n\n皮普写道：我总是休息。下周我有时会跳一跳。大家都笑了，然后订了一个计划。",
        },
        practice: [
          { type: "choice", q: "How often does Tom exercise?", options: ["Every day.", "Hardly ever.", "Once a year."], answer: 0 },
          { type: "choice", q: "hardly ever 的意思最接近：", options: ["经常", "几乎不", "总是"], answer: 1 },
          { type: "fill", q: "Lily usually plays ping-pong _____ a week.", answer: "twice", hint: "两次" },
          { type: "order", words: ["often", "How", "you", "do", "exercise", "?"], answer: "How often do you exercise?" },
          { type: "tf", q: "Maya never eats junk food at night.", answer: true },
          { type: "listen", audio: "I usually play ping-pong twice a week.", options: ["I usually play ping-pong twice a week.", "I always sleep after dinner.", "I never do housework."], answer: 0 },
        ],
        fun: {
          title: "Frequency ladder",
          titleZh: "频率梯子",
          chant: [
            "Always, usually, often, then",
            "Sometimes, hardly ever, never again.",
            "How often? Once, twice, three times a week.",
            "Move your body. That's what we seek!",
          ],
        },
      },

      {
        id: 3,
        title: "I'm More Outgoing",
        titleZh: "我更外向",
        theme: "compare",
        color: "#7b5ea7",
        emoji: "🤝",
        goals: [
          "用比较级描述人和事物",
          "使用 than 和 as ... as",
          "读一篇双胞胎朋友的短文",
        ],
        dialogue: {
          title: "Two Kinds of Friends",
          titleZh: "两种朋友",
          scene: "The class talks about partners for a science project.",
          sceneZh: "全班在讨论科学项目的搭档。",
          lines: [
            { speaker: "Lily", text: "Maya is quieter than I am, but she is more hard-working.", zh: "玛雅比我文静，但她更勤奋。" },
            { speaker: "Tom", text: "Ben is funnier than me. He is also taller.", zh: "本比我更有趣。他也更高。" },
            { speaker: "Ben", text: "Tom is more outgoing. I get shy in a big group.", zh: "汤姆更外向。人多的时候我会害羞。" },
            { speaker: "Maya", text: "I'm not as loud as Tom, but I can draw better than him.", zh: "我没有汤姆那么大声，但我画画比他好。" },
            { speaker: "Pip", text: "I am smaller than everyone. Is that useful?", zh: "我比谁都小。这有用吗？" },
            { speaker: "Ms. Green", text: "Yes. Different is useful. A good team is not the same in every way.", zh: "有用。不同就是有用。好团队不必处处相同。" },
            { speaker: "Lily", text: "So Maya and I can work together. She is more careful. I am faster.", zh: "那玛雅可以和我一组。她更细心。我更快。" },
          ],
        },
        vocab: [
          { en: "outgoing", ipa: "/ˈaʊtɡəʊɪŋ/", zh: "外向的", example: "Tom is more outgoing than Ben.", exampleZh: "汤姆比本更外向。" },
          { en: "quiet", ipa: "/ˈkwaɪət/", zh: "文静的", example: "Maya is quieter than Lily.", exampleZh: "玛雅比莉莉更文静。" },
          { en: "hard-working", ipa: "/ˌhɑːd ˈwɜːkɪŋ/", zh: "勤奋的", example: "Maya is more hard-working.", exampleZh: "玛雅更勤奋。" },
          { en: "talented", ipa: "/ˈtæləntɪd/", zh: "有才能的", example: "Ben is talented at telling jokes.", exampleZh: "本很会讲笑话。" },
          { en: "serious", ipa: "/ˈsɪəriəs/", zh: "严肃的", example: "Ms. Green looks serious, but she is kind.", exampleZh: "格林老师看起来严肃，但很亲切。" },
          { en: "loudly", ipa: "/ˈlaʊdli/", zh: "大声地", example: "Tom talks more loudly than Maya.", exampleZh: "汤姆说话比玛雅大声。" },
          { en: "better", ipa: "/ˈbetə(r)/", zh: "更好（good 的比较级）", example: "Maya can draw better than Tom.", exampleZh: "玛雅画画比汤姆好。" },
          { en: "both", ipa: "/bəʊθ/", zh: "两者都", example: "Both friends are helpful.", exampleZh: "两个朋友都很乐于助人。" },
        ],
        grammar: {
          title: "more ... than / as ... as",
          titleZh: "比较级",
          pattern: "A is + 比较级 + than B.   A is as + 原级 + as B.",
          notes: [
            "短形容词加 -er：tall → taller, quiet → quieter。",
            "长形容词用 more：more outgoing, more hard-working。",
            "as ... as 表示“和……一样”：I'm not as loud as Tom.",
          ],
          examples: [
            { en: "Maya is quieter than Lily, but she is more hard-working.", zh: "玛雅比莉莉文静，但她更勤奋。" },
            { en: "Tom is more outgoing than Ben.", zh: "汤姆比本更外向。" },
            { en: "I'm not as loud as Tom, but I can draw better.", zh: "我没有汤姆那么大声，但我画画更好。" },
          ],
        },
        reading: {
          title: "Not the Same, Still a Team",
          titleZh: "不一样，仍是一队",
          text: "Lily and Maya are both fourteen, but they are not the same. Lily is more outgoing. She talks to new students first. Maya is quieter and more careful. She checks every number twice.\n\nTom is taller and funnier than Ben. Ben is more serious about science. He is not as loud as Tom, but he is talented at making small machines.\n\n\"Who is better?\" Pip asks. Ms. Green shakes her head. \"Better at what? A team needs both. One friend is faster. One friend is more careful. Together they are stronger.\"\n\nThat afternoon, the four of them finished the project earlier than the other groups.",
          textZh:
            "莉莉和玛雅都十四岁，但她们并不一样。莉莉更外向，会先和新同学说话。玛雅更文静、更细心，每个数字都要检查两遍。\n\n汤姆比本更高、更有趣。本对科学更认真。他没有汤姆那么大声，但很会做小机器。\n\n“谁更好？”皮普问。格林老师摇摇头：“哪一方面更好？团队两种人都需要。一个更快，一个更细心。在一起他们更强。”\n\n那天下午，他们四个比其他组更早完成了项目。",
        },
        practice: [
          { type: "choice", q: "Who is more outgoing?", options: ["Maya", "Lily", "Pip"], answer: 1 },
          { type: "choice", q: "outgoing 的比较级是：", options: ["outgoinger", "more outgoing", "most outgoing"], answer: 1 },
          { type: "fill", q: "Maya is not as loud _____ Tom.", answer: "as", hint: "as ... as" },
          { type: "order", words: ["more", "Tom", "is", "outgoing", "."], answer: "Tom is more outgoing." },
          { type: "tf", q: "A good team needs friends who are the same in every way.", answer: false },
          { type: "listen", audio: "Maya is quieter than Lily.", options: ["Maya is quieter than Lily.", "Tom is quieter than Maya.", "Ben is taller than everyone."], answer: 0 },
        ],
        fun: {
          title: "Compare it",
          titleZh: "比一比",
          chant: [
            "Taller, quieter, more outgoing,",
            "Better, faster — keep it going.",
            "As kind as you, as brave as me,",
            "Different friends make a stronger we.",
          ],
        },
      },

      {
        id: 4,
        title: "What's the Best Place?",
        titleZh: "最好的地方是哪儿？",
        theme: "town",
        color: "#c45c6a",
        emoji: "🎬",
        goals: [
          "用最高级评价地点和事物",
          "问答：What's the best ...?",
          "读一篇小镇指南",
        ],
        dialogue: {
          title: "Saturday Plans",
          titleZh: "周六计划",
          scene: "The friends choose a place for Saturday afternoon.",
          sceneZh: "朋友们在选星期六下午去哪儿。",
          lines: [
            { speaker: "Tom", text: "What's the best movie theater in town?", zh: "镇上最好的电影院是哪家？" },
            { speaker: "Lily", text: "Screen House. It has the biggest screen and the most comfortable seats.", zh: "银幕屋。它的屏幕最大，座位也最舒服。" },
            { speaker: "Ben", text: "But it's the most expensive. Star Cinema is cheaper and closer.", zh: "但它最贵。星星影院更便宜，也更近。" },
            { speaker: "Maya", text: "What's the best clothing store? I need a new jacket.", zh: "最好的服装店是哪家？我需要一件新夹克。" },
            { speaker: "Lily", text: "Blue Street has the worst service. Don't go there.", zh: "蓝街那家服务最差。别去那儿。" },
            { speaker: "Pip", text: "The best place is the park. It's the closest, and the snacks are free if you find them!", zh: "最好的地方是公园。它最近，零食找到了还免费！" },
            { speaker: "Ms. Green", text: "Choose carefully. The cheapest is not always the worst. The closest is not always the best.", zh: "仔细选。最便宜的不一定最差。最近的也不一定最好。" },
          ],
        },
        vocab: [
          { en: "comfortable", ipa: "/ˈkʌmftəbl/", zh: "舒适的", example: "These are the most comfortable seats.", exampleZh: "这些是最舒服的座位。" },
          { en: "expensive", ipa: "/ɪkˈspensɪv/", zh: "昂贵的", example: "Screen House is the most expensive.", exampleZh: "银幕屋最贵。" },
          { en: "cheap", ipa: "/tʃiːp/", zh: "便宜的", example: "Star Cinema is cheaper.", exampleZh: "星星影院更便宜。" },
          { en: "close", ipa: "/kləʊs/", zh: "近的", example: "The park is the closest place.", exampleZh: "公园是最近的地方。" },
          { en: "service", ipa: "/ˈsɜːvɪs/", zh: "服务", example: "Blue Street has the worst service.", exampleZh: "蓝街那家服务最差。" },
          { en: "theater", ipa: "/ˈθɪətə(r)/", zh: "剧院；电影院", example: "What's the best movie theater?", exampleZh: "最好的电影院是哪家？" },
          { en: "fresh", ipa: "/freʃ/", zh: "新鲜的", example: "This shop has the freshest fruit.", exampleZh: "这家店的水果最新鲜。" },
          { en: "worst", ipa: "/wɜːst/", zh: "最差的", example: "Don't choose the worst service.", exampleZh: "不要选服务最差的。" },
        ],
        grammar: {
          title: "What's the best ...?",
          titleZh: "最高级",
          pattern: "What's the + 最高级 + 名词? — It's the biggest / the most comfortable ...",
          notes: [
            "短形容词加 -est：big → biggest, close → closest。",
            "长形容词用 the most：the most comfortable, the most expensive。",
            "不规则：good → better → best；bad → worse → worst。",
          ],
          examples: [
            { en: "What's the best movie theater? — Screen House.", zh: "最好的电影院是哪家？——银幕屋。" },
            { en: "It has the biggest screen and the most comfortable seats.", zh: "它的屏幕最大，座位也最舒服。" },
            { en: "Blue Street has the worst service.", zh: "蓝街那家服务最差。" },
          ],
        },
        reading: {
          title: "A Mini Guide to Our Town",
          titleZh: "我们小镇迷你指南",
          text: "Our town is not big, but it has choices. Screen House is the best movie theater if you want the biggest screen. It is also the most expensive. Star Cinema is cheaper and closer to school.\n\nGreen Market has the freshest fruit. Blue Street Store is the closest clothing shop, but it has the worst service. Maya says the best jackets are in the old street behind the library.\n\nThe park is the quietest place after four o'clock. Pip thinks it is the best place in town. \"The tickets are free,\" he says, \"and the trees don't talk loudly.\"\n\nWhat's the best place for you? It depends on what you need.",
          textZh:
            "我们的小镇不大，但有得选。如果你想看最大的屏幕，银幕屋是最好的电影院。它也最贵。星星影院更便宜，离学校也更近。\n\n绿市的水果最新鲜。蓝街服装店是最近的服装店，但服务最差。玛雅说最好的夹克在图书馆后面的老街。\n\n四点以后，公园是最安静的地方。皮普觉得那是镇上最好的地方。“门票免费，”他说，“而且树不会大声说话。”\n\n对你来说最好的地方是哪儿？这取决于你需要什么。",
        },
        practice: [
          { type: "choice", q: "Which theater has the biggest screen?", options: ["Star Cinema", "Screen House", "Blue Street"], answer: 1 },
          { type: "choice", q: "comfortable 的最高级是：", options: ["comfortablest", "the most comfortable", "more comfortable"], answer: 1 },
          { type: "fill", q: "Blue Street has the _____ service.", answer: "worst", hint: "最差的" },
          { type: "order", words: ["best", "What's", "the", "theater", "movie", "?"], answer: "What's the best movie theater?" },
          { type: "tf", q: "The cheapest place is always the worst place.", answer: false },
          { type: "listen", audio: "It has the most comfortable seats.", options: ["It has the most comfortable seats.", "It has the worst fruit.", "It has the closest tickets."], answer: 0 },
        ],
        fun: {
          title: "Best, better, good",
          titleZh: "好，更好，最好",
          chant: [
            "Good, better, best — never rest.",
            "Bad, worse, worst — think first.",
            "Closest, cheapest, most comfortable chair,",
            "Choose the place that takes you there.",
          ],
        },
      },

      {
        id: 5,
        title: "Do You Want to Watch a Show?",
        titleZh: "你想看节目吗？",
        theme: "media",
        color: "#e07a3d",
        emoji: "📺",
        goals: [
          "谈论电视节目和爱好",
          "使用 want to / like to + 动词",
          "礼貌地发出或拒绝邀请",
        ],
        dialogue: {
          title: "Friday Night",
          titleZh: "星期五晚上",
          scene: "The friends plan what to watch after dinner.",
          sceneZh: "朋友们在计划晚饭后看什么。",
          lines: [
            { speaker: "Tom", text: "Do you want to watch a game show tonight?", zh: "今晚你想看游戏节目吗？" },
            { speaker: "Lily", text: "Not really. I don't mind game shows, but I prefer talent shows.", zh: "不太想。游戏节目我无所谓，但我更喜欢才艺秀。" },
            { speaker: "Maya", text: "I like to watch the news. I want to know what happened today.", zh: "我喜欢看新闻。我想知道今天发生了什么。" },
            { speaker: "Ben", text: "Sitcoms make me laugh. Let's watch one together.", zh: "情景喜剧让我发笑。我们一起看一集吧。" },
            { speaker: "Pip", text: "I want to watch cartoons. They are educational. Really!", zh: "我想看动画片。它们很有教育意义。真的！" },
            { speaker: "Lily", text: "Why don't we watch a short talent show first, then a sitcom?", zh: "我们为什么不先看一小段才艺秀，再看情景喜剧？" },
            { speaker: "Tom", text: "Good plan. I can't stand long news at night.", zh: "好主意。晚上我受不了很长的新闻。" },
          ],
        },
        vocab: [
          { en: "game show", ipa: "/ɡeɪm ʃəʊ/", zh: "游戏节目", example: "Do you want to watch a game show?", exampleZh: "你想看游戏节目吗？" },
          { en: "talent show", ipa: "/ˈtælənt ʃəʊ/", zh: "才艺表演节目", example: "Lily prefers talent shows.", exampleZh: "莉莉更喜欢才艺秀。" },
          { en: "sitcom", ipa: "/ˈsɪtkɒm/", zh: "情景喜剧", example: "Sitcoms make Ben laugh.", exampleZh: "情景喜剧让本发笑。" },
          { en: "news", ipa: "/njuːz/", zh: "新闻", example: "Maya likes to watch the news.", exampleZh: "玛雅喜欢看新闻。" },
          { en: "cartoon", ipa: "/kɑːˈtuːn/", zh: "动画片", example: "Pip wants to watch cartoons.", exampleZh: "皮普想看动画片。" },
          { en: "mind", ipa: "/maɪnd/", zh: "介意", example: "I don't mind game shows.", exampleZh: "游戏节目我无所谓。" },
          { en: "stand", ipa: "/stænd/", zh: "忍受", example: "I can't stand long news at night.", exampleZh: "晚上我受不了很长的新闻。" },
          { en: "plan", ipa: "/plæn/", zh: "计划", example: "They plan to watch a sitcom.", exampleZh: "他们计划看一集情景喜剧。" },
        ],
        grammar: {
          title: "want to / like to",
          titleZh: "表达想做的事",
          pattern: "Do you want to + 动词? — I want to / I'd like to / I don't mind / I can't stand ...",
          notes: [
            "want to, like to, plan to 后面用动词原形。",
            "Why don't we ...? 用来提出建议。",
            "can't stand 表示“受不了”，语气比 don't like 更强。",
          ],
          examples: [
            { en: "Do you want to watch a game show? — Not really.", zh: "你想看游戏节目吗？——不太想。" },
            { en: "I like to watch the news. I want to know what happened.", zh: "我喜欢看新闻。我想知道发生了什么。" },
            { en: "Why don't we watch a sitcom together?", zh: "我们为什么不一起看情景喜剧？" },
          ],
        },
        reading: {
          title: "What We Watch",
          titleZh: "我们看什么",
          text: "Friday night is screen night in Class 8. Tom wants to watch a game show because he likes to shout out the answers. Lily prefers talent shows. She says they are more educational than game shows.\n\nMaya likes to watch the news. She wants to understand the world, not only jokes. Ben can't stand sad films, so he always chooses sitcoms.\n\nPip has a plan. \"Why don't we take turns?\" he says. \"Ten minutes of news, ten minutes of a talent show, then a sitcom. Cartoons can wait.\"\n\nThey try his plan. It is not perfect, but nobody is bored. The best show, Maya writes later, is the one you share.",
          textZh:
            "星期五晚上是八班的屏幕之夜。汤姆想看游戏节目，因为他喜欢大声喊出答案。莉莉更喜欢才艺秀。她说那比游戏节目更有教育意义。\n\n玛雅喜欢看新闻。她想理解世界，而不只是听笑话。本受不了悲伤的电影，所以他总是选情景喜剧。\n\n皮普有一个计划。“我们为什么不轮流看？”他说，“十分钟新闻，十分钟才艺秀，然后看情景喜剧。动画片可以等。”\n\n他们试了他的计划。并不完美，但没有人觉得无聊。玛雅后来写道：最好的节目，是你愿意分享的那一个。",
        },
        practice: [
          { type: "choice", q: "What does Maya like to watch?", options: ["Cartoons", "The news", "Sad films"], answer: 1 },
          { type: "choice", q: "I can't stand 的意思最接近：", options: ["我站不起来", "我受不了", "我不能理解"], answer: 1 },
          { type: "fill", q: "Do you want _____ watch a sitcom tonight?", answer: "to", hint: "want to" },
          { type: "order", words: ["don't", "Why", "we", "watch", "a", "sitcom", "?"], answer: "Why don't we watch a sitcom?" },
          { type: "tf", q: "Lily prefers talent shows to game shows.", answer: true },
          { type: "listen", audio: "I can't stand long news at night.", options: ["I can't stand long news at night.", "I always watch sad films.", "I never want to watch a show."], answer: 0 },
        ],
        fun: {
          title: "Show time",
          titleZh: "节目时间",
          chant: [
            "Game show, talent show, news and sitcom,",
            "Want to watch? Come on, come on!",
            "I don't mind this. I can't stand that.",
            "Why don't we share the remote — how about that?",
          ],
        },
      },

      {
        id: 6,
        title: "I'm Going to Study Computer Science",
        titleZh: "我打算学计算机",
        theme: "future-plans",
        color: "#4aa3a8",
        emoji: "💻",
        goals: [
          "用 be going to 谈论打算",
          "讨论理想职业和新年计划",
          "读一篇关于未来工作的短文",
        ],
        dialogue: {
          title: "After Junior High",
          titleZh: "初中之后",
          scene: "Career day. Students write their plans on coloured cards.",
          sceneZh: "职业日。同学们把打算写在彩色卡片上。",
          lines: [
            { speaker: "Ms. Green", text: "What are you going to be when you grow up, Ben?", zh: "本，你长大后打算做什么？" },
            { speaker: "Ben", text: "I'm going to study computer science. I want to make useful apps.", zh: "我打算学计算机。我想做有用的应用。" },
            { speaker: "Lily", text: "I'm going to be a doctor. I'm going to work in a small town.", zh: "我打算当医生。我打算在小镇工作。" },
            { speaker: "Maya", text: "I'm going to write for a newspaper. I like questions.", zh: "我打算为报纸写稿。我喜欢提问。" },
            { speaker: "Tom", text: "I'm going to be a PE teacher. I'm going to keep people moving.", zh: "我打算当体育老师。我要让大家动起来。" },
            { speaker: "Pip", text: "I'm going to be a travel fox. First I'm going to learn maps.", zh: "我打算当旅行狐狸。首先我要学认地图。" },
            { speaker: "Ms. Green", text: "Good. Write how you are going to start this year, not only someday.", zh: "很好。写下今年你打算怎样开始，而不只是“有一天”。" },
          ],
        },
        vocab: [
          { en: "computer science", ipa: "/kəmˈpjuːtə ˈsaɪəns/", zh: "计算机科学", example: "Ben is going to study computer science.", exampleZh: "本打算学计算机科学。" },
          { en: "engineer", ipa: "/ˌendʒɪˈnɪə(r)/", zh: "工程师", example: "She is going to be an engineer.", exampleZh: "她打算当工程师。" },
          { en: "doctor", ipa: "/ˈdɒktə(r)/", zh: "医生", example: "Lily is going to be a doctor.", exampleZh: "莉莉打算当医生。" },
          { en: "journalist", ipa: "/ˈdʒɜːnəlɪst/", zh: "记者", example: "Maya wants to be a journalist.", exampleZh: "玛雅想当记者。" },
          { en: "resolution", ipa: "/ˌrezəˈluːʃn/", zh: "决心；计划", example: "My New Year's resolution is to read more.", exampleZh: "我的新年决心是多读书。" },
          { en: "grow up", ipa: "/ɡrəʊ ʌp/", zh: "长大", example: "What are you going to be when you grow up?", exampleZh: "你长大后打算做什么？" },
          { en: "college", ipa: "/ˈkɒlɪdʒ/", zh: "大学；学院", example: "He is going to college in four years.", exampleZh: "四年后他会上大学。" },
          { en: "promise", ipa: "/ˈprɒmɪs/", zh: "承诺", example: "Don't promise too much. Start small.", exampleZh: "不要承诺太多。从小处开始。" },
        ],
        grammar: {
          title: "be going to",
          titleZh: "谈论打算",
          pattern: "主语 + am / is / are going to + 动词原形.",
          notes: [
            "be going to 表示已经打算或能预见的将来。",
            "问句把 be 提前：What are you going to be?",
            "否定：I'm not going to stay at home all weekend.",
          ],
          examples: [
            { en: "I'm going to study computer science.", zh: "我打算学计算机科学。" },
            { en: "What are you going to be when you grow up?", zh: "你长大后打算做什么？" },
            { en: "She is going to work in a small town.", zh: "她打算在小镇工作。" },
          ],
        },
        reading: {
          title: "A Card on the Wall",
          titleZh: "墙上的卡片",
          text: "On career day, Class 8 puts cards on the wall. Ben writes: I'm going to study computer science. I'm going to make an app that helps old people call their families.\n\nLily is going to be a doctor. This year she is going to read one health article every week. Maya is going to be a journalist. She is going to ask better questions in English class.\n\nTom is going to be a PE teacher. His resolution is simple: I'm going to exercise with Ben three times a week.\n\nPip's card is small. \"I'm going to learn twenty new words. Then I'm going to grow up a little.\"\n\nMs. Green smiles. \"A job is far away. A good week is close. Keep your promise to this week.\"",
          textZh:
            "职业日，八班把卡片贴在墙上。本写道：我打算学计算机。我要做一个帮老人给家人打电话的应用。\n\n莉莉打算当医生。今年她打算每周读一篇健康文章。玛雅打算当记者。她打算在英语课上提出更好的问题。\n\n汤姆打算当体育老师。他的决心很简单：我打算每周和本一起锻炼三次。\n\n皮普的卡片很小：“我打算学会二十个新词。然后我再长大一点点。”\n\n格林老师笑了：“职业还很远。好好过一周却很近。先遵守对本周的承诺。”",
        },
        practice: [
          { type: "choice", q: "What is Ben going to study?", options: ["Medicine", "Computer science", "Art history"], answer: 1 },
          { type: "choice", q: "be going to 后面的动词要用：", options: ["原形", "过去式", "-ing 形式"], answer: 0 },
          { type: "fill", q: "I _____ going to be a doctor.", answer: "am", hint: "I 后面的 be" },
          { type: "order", words: ["going", "I'm", "to", "study", "science", "computer", "."], answer: "I'm going to study computer science." },
          { type: "tf", q: "Tom's resolution is to exercise with Ben three times a week.", answer: true },
          { type: "listen", audio: "I'm going to study computer science.", options: ["I'm going to study computer science.", "I'm going to stay at home all day.", "I'm going to forget my promise."], answer: 0 },
        ],
        fun: {
          title: "Future steps",
          titleZh: "未来的脚步",
          chant: [
            "I'm going to try. I'm going to learn.",
            "I'm going to wait, then take my turn.",
            "Doctor, teacher, engineer,",
            "Start this week. The future is here.",
          ],
        },
      },

      {
        id: 7,
        title: "Will People Have Robots?",
        titleZh: "人们会有机器人吗？",
        theme: "predictions",
        color: "#3b8f4f",
        emoji: "🤖",
        goals: [
          "用 will / won't 预测将来",
          "谈论科技、环境和生活变化",
          "读一篇关于未来城市的短文",
        ],
        dialogue: {
          title: "The Year 2050",
          titleZh: "2050 年",
          scene: "Science class. Students make predictions about the future.",
          sceneZh: "科学课上，同学们预测未来。",
          lines: [
            { speaker: "Ms. Green", text: "Will people have robots in their homes?", zh: "人们家里会有机器人吗？" },
            { speaker: "Ben", text: "Yes, they will. Robots will cook and clean. They won't feel tired.", zh: "会的。机器人会做饭、打扫。它们不会觉得累。" },
            { speaker: "Maya", text: "There will be less paper money. Everything will be on phones.", zh: "纸币会更少。一切都会在手机上。" },
            { speaker: "Lily", text: "Will there be more pollution? I hope not.", zh: "污染会更多吗？我希望不会。" },
            { speaker: "Tom", text: "People will live longer, but they will still need parks.", zh: "人会活得更长，但仍然需要公园。" },
            { speaker: "Pip", text: "Will foxes have homework? I hope they won't!", zh: "狐狸会有作业吗？我希望不会！" },
            { speaker: "Ms. Green", text: "We will not know everything. But we can work for a cleaner city now.", zh: "我们不会知道一切。但我们现在就能为更干净的城市努力。" },
          ],
        },
        vocab: [
          { en: "robot", ipa: "/ˈrəʊbɒt/", zh: "机器人", example: "Will people have robots at home?", exampleZh: "人们家里会有机器人吗？" },
          { en: "prediction", ipa: "/prɪˈdɪkʃn/", zh: "预测", example: "Make a prediction about 2050.", exampleZh: "对 2050 年做一个预测。" },
          { en: "pollution", ipa: "/pəˈluːʃn/", zh: "污染", example: "There will be less pollution if we try.", exampleZh: "如果我们努力，污染会更少。" },
          { en: "paper money", ipa: "/ˈpeɪpə ˈmʌni/", zh: "纸币", example: "There will be less paper money.", exampleZh: "纸币会更少。" },
          { en: "probably", ipa: "/ˈprɒbəbli/", zh: "很可能", example: "People will probably live longer.", exampleZh: "人们很可能会活得更长。" },
          { en: "even", ipa: "/ˈiːvn/", zh: "甚至", example: "Even small towns will have fast internet.", exampleZh: "甚至小镇也会有快速网络。" },
          { en: "believe", ipa: "/bɪˈliːv/", zh: "相信", example: "I believe parks will still matter.", exampleZh: "我相信公园仍然重要。" },
          { en: "future", ipa: "/ˈfjuːtʃə(r)/", zh: "将来", example: "The future will need kind people.", exampleZh: "未来需要善良的人。" },
        ],
        grammar: {
          title: "will / won't",
          titleZh: "预测将来",
          pattern: "主语 + will / won't + 动词原形.   Will + 主语 + 动词原形?",
          notes: [
            "will 表示预测或临时决定，后面用动词原形。",
            "否定是 will not 或 won't。",
            "there will be 表示“将会有”：There will be less paper money.",
          ],
          examples: [
            { en: "Will people have robots? — Yes, they will.", zh: "人们会有机器人吗？——会的。" },
            { en: "Robots will cook. They won't feel tired.", zh: "机器人会做饭。它们不会觉得累。" },
            { en: "There will be less paper money.", zh: "纸币会更少。" },
          ],
        },
        reading: {
          title: "A City in 2050",
          titleZh: "2050 年的一座城",
          text: "Class 8 writes about the future. Ben believes people will have robots at home. The robots will cook simple meals. They won't replace friends.\n\nMaya thinks there will be less paper money. People will pay with phones. Even small shops will do this. Tom says people will probably live longer, so cities will need more parks, not only more buildings.\n\nLily is worried about pollution. \"If we do nothing, there will be more of it,\" she writes. \"If we plant trees now, the future will be cleaner.\"\n\nPip adds one line: \"I will still need a quiet corner. The future can be fast, but a fox needs a rest.\"",
          textZh:
            "八班在写未来。本相信人们家里会有机器人。机器人会做简单的饭。它们不会取代朋友。\n\n玛雅觉得纸币会更少。人们会用手机付款。甚至小店也会这样。汤姆说人们很可能会活得更长，所以城市会需要更多公园，而不只是更多楼房。\n\n莉莉担心污染。“如果我们什么都不做，污染会更多，”她写道，“如果我们现在种树，未来会更干净。”\n\n皮普加了一句：“我仍然需要一个安静的角落。未来可以很快，但狐狸需要休息。”",
        },
        practice: [
          { type: "choice", q: "What does Ben believe about robots?", options: ["They will replace friends.", "They will cook and they won't feel tired.", "They will never exist."], answer: 1 },
          { type: "choice", q: "won't 等于：", options: ["will not", "want not", "was not"], answer: 0 },
          { type: "fill", q: "There _____ be less paper money in the future.", answer: "will", hint: "将来会有" },
          { type: "order", words: ["people", "Will", "have", "robots", "?"], answer: "Will people have robots?" },
          { type: "tf", q: "Lily thinks doing nothing will make more pollution.", answer: true },
          { type: "listen", audio: "There will be less paper money.", options: ["There will be less paper money.", "There will be more junk food.", "There will be no parks."], answer: 0 },
        ],
        fun: {
          title: "Will we?",
          titleZh: "我们会吗？",
          chant: [
            "Will we fly? Will we try?",
            "Will the rivers still run by?",
            "Robots cook. People care.",
            "The future needs us everywhere.",
          ],
        },
      },

      {
        id: 8,
        title: "How Do You Make a Milk Shake?",
        titleZh: "奶昔怎么做？",
        theme: "process",
        color: "#d4a017",
        emoji: "🍌",
        goals: [
          "用 first / next / then / finally 说明步骤",
          "区分可数与不可数，how much / how many",
          "读一篇厨房短文",
        ],
        dialogue: {
          title: "In the School Kitchen",
          titleZh: "在学校厨房",
          scene: "Cooking club. Lily reads the steps out loud.",
          sceneZh: "烹饪社。莉莉大声读出步骤。",
          lines: [
            { speaker: "Lily", text: "How do you make a banana milk shake?", zh: "香蕉奶昔怎么做？" },
            { speaker: "Ms. Green", text: "First, peel two bananas. Next, put them in the blender.", zh: "首先，剥两根香蕉。接着，放进搅拌机。" },
            { speaker: "Tom", text: "How much yogurt do we need?", zh: "我们需要多少酸奶？" },
            { speaker: "Ms. Green", text: "About one cup. Then pour in some milk. Finally, mix it.", zh: "大约一杯。然后倒一些牛奶。最后搅拌。" },
            { speaker: "Ben", text: "How many cups do we have? I only see one.", zh: "我们有多少个杯子？我只看到一个。" },
            { speaker: "Maya", text: "Don't turn on the blender before you close it. That's important.", zh: "盖子盖好之前不要开搅拌机。这一点很重要。" },
            { speaker: "Pip", text: "Finally, pour a little for the cook. That's me.", zh: "最后，给厨师倒一点。也就是我。" },
          ],
        },
        vocab: [
          { en: "milk shake", ipa: "/mɪlk ʃeɪk/", zh: "奶昔", example: "How do you make a banana milk shake?", exampleZh: "香蕉奶昔怎么做？" },
          { en: "peel", ipa: "/piːl/", zh: "剥皮", example: "First, peel two bananas.", exampleZh: "首先，剥两根香蕉。" },
          { en: "pour", ipa: "/pɔː(r)/", zh: "倒", example: "Then pour in some milk.", exampleZh: "然后倒一些牛奶。" },
          { en: "yogurt", ipa: "/ˈjɒɡət/", zh: "酸奶", example: "How much yogurt do we need?", exampleZh: "我们需要多少酸奶？" },
          { en: "blender", ipa: "/ˈblendə(r)/", zh: "搅拌机", example: "Put the fruit in the blender.", exampleZh: "把水果放进搅拌机。" },
          { en: "finally", ipa: "/ˈfaɪnəli/", zh: "最后", example: "Finally, mix it and drink.", exampleZh: "最后搅拌并喝掉。" },
          { en: "ingredient", ipa: "/ɪnˈɡriːdiənt/", zh: "食材；原料", example: "We need only four ingredients.", exampleZh: "我们只需要四种食材。" },
          { en: "add", ipa: "/æd/", zh: "加入", example: "Add a little honey if you like.", exampleZh: "喜欢的话加一点蜂蜜。" },
        ],
        grammar: {
          title: "How do you make ...?",
          titleZh: "说明做法；how much / how many",
          pattern: "First, ... Next, ... Then, ... Finally, ...    How much + 不可数?  How many + 复数?",
          notes: [
            "步骤词帮助读者跟上顺序：first, next, then, finally。",
            "yogurt, milk, honey 不可数，用 how much。",
            "bananas, cups 可数，用 how many。",
          ],
          examples: [
            { en: "First, peel two bananas. Next, put them in the blender.", zh: "首先剥两根香蕉。接着放进搅拌机。" },
            { en: "How much yogurt do we need? — One cup.", zh: "我们需要多少酸奶？——一杯。" },
            { en: "How many bananas do you need? — Two.", zh: "你需要多少根香蕉？——两根。" },
          ],
        },
        reading: {
          title: "Banana Milk Shake for Four",
          titleZh: "四人份香蕉奶昔",
          text: "Cooking club wants a drink for four people. The ingredients are simple: two bananas, one cup of yogurt, some milk and a little honey.\n\nFirst, peel the bananas and cut them. Next, put them into the blender. Then pour in the yogurt and the milk. How much milk? Not too much — about half a cup. Finally, add honey and mix.\n\nBen asks, \"How many cups do we need?\" Maya counts four. Pip counts five. \"The fifth is for the teacher,\" he says.\n\nThey close the blender before they turn it on. The milk shake is cold and sweet. \"Next week,\" Lily says, \"we will make dumplings. First, we will wash our hands.\"",
          textZh:
            "烹饪社想做四人份的饮料。食材很简单：两根香蕉、一杯酸奶、一些牛奶和一点蜂蜜。\n\n首先，剥香蕉并切开。接着放进搅拌机。然后倒入酸奶和牛奶。多少牛奶？不要太多——大约半杯。最后加蜂蜜并搅拌。\n\n本问：“我们需要多少个杯子？”玛雅数了四个。皮普数了五个。“第五杯给老师，”他说。\n\n他们先盖上盖子再开机。奶昔又凉又甜。“下周，”莉莉说，“我们包饺子。首先，我们洗手。”",
        },
        practice: [
          { type: "choice", q: "What do you do first to make the milk shake?", options: ["Pour honey on the table.", "Peel two bananas.", "Turn on the blender with the lid open."], answer: 1 },
          { type: "choice", q: "yogurt 是不可数名词，应问：", options: ["How many yogurt?", "How much yogurt?", "How often yogurt?"], answer: 1 },
          { type: "fill", q: "_____ , mix it and then drink.", answer: "Finally", hint: "最后" },
          { type: "order", words: ["do", "How", "you", "make", "a", "shake", "milk", "?"], answer: "How do you make a milk shake?" },
          { type: "tf", q: "You should close the blender before you turn it on.", answer: true },
          { type: "listen", audio: "How much yogurt do we need?", options: ["How much yogurt do we need?", "How many robots do we need?", "How often do we pour honey?"], answer: 0 },
        ],
        fun: {
          title: "Kitchen steps",
          titleZh: "厨房步骤",
          chant: [
            "First we peel. Next we pour.",
            "Then we mix, and ask for more.",
            "How much milk? How many cups?",
            "Finally smile — and drink it up!",
          ],
        },
      },

      {
        id: 9,
        title: "What's the Matter?",
        titleZh: "怎么了？",
        theme: "health",
        color: "#c23b5a",
        emoji: "🤒",
        goals: [
          "描述身体不适并提出建议",
          "使用 should / shouldn't",
          "读一篇校医室故事",
        ],
        dialogue: {
          title: "At the School Clinic",
          titleZh: "在校医室",
          scene: "Tuesday. Tom looks pale. Maya walks him to the clinic.",
          sceneZh: "星期二。汤姆脸色苍白。玛雅送他去校医室。",
          lines: [
            { speaker: "Maya", text: "What's the matter, Tom? You don't look well.", zh: "汤姆，你怎么了？你看起来不太舒服。" },
            { speaker: "Tom", text: "I have a headache and a sore throat. I feel tired.", zh: "我头疼，嗓子也疼。我觉得很累。" },
            { speaker: "Ms. Green", text: "You should drink warm water. You shouldn't run in PE today.", zh: "你应该喝温水。今天体育课不该跑步。" },
            { speaker: "Nurse", text: "Do you have a fever? Let me check.", zh: "你发烧了吗？我来量一下。" },
            { speaker: "Tom", text: "I don't think so. I ate too much ice cream last night.", zh: "我想没有。我昨晚冰淇淋吃太多了。" },
            { speaker: "Nurse", text: "Then you should rest. Lie down for twenty minutes.", zh: "那你应该休息。躺二十分钟。" },
            { speaker: "Pip", text: "Should I bring him a banana milk shake? Maybe later.", zh: "我该给他带杯香蕉奶昔吗？也许以后吧。" },
          ],
        },
        vocab: [
          { en: "matter", ipa: "/ˈmætə(r)/", zh: "问题；麻烦", example: "What's the matter?", exampleZh: "怎么了？" },
          { en: "headache", ipa: "/ˈhedeɪk/", zh: "头痛", example: "Tom has a headache.", exampleZh: "汤姆头疼。" },
          { en: "sore throat", ipa: "/sɔː θrəʊt/", zh: "嗓子疼", example: "I have a sore throat.", exampleZh: "我嗓子疼。" },
          { en: "fever", ipa: "/ˈfiːvə(r)/", zh: "发烧", example: "Do you have a fever?", exampleZh: "你发烧了吗？" },
          { en: "stomachache", ipa: "/ˈstʌməkeɪk/", zh: "胃痛；肚子疼", example: "Junk food can give you a stomachache.", exampleZh: "垃圾食品可能让你肚子疼。" },
          { en: "should", ipa: "/ʃʊd/", zh: "应该", example: "You should drink warm water.", exampleZh: "你应该喝温水。" },
          { en: "rest", ipa: "/rest/", zh: "休息", example: "You should rest for a while.", exampleZh: "你应该休息一会儿。" },
          { en: "lie down", ipa: "/laɪ daʊn/", zh: "躺下", example: "Lie down for twenty minutes.", exampleZh: "躺二十分钟。" },
        ],
        grammar: {
          title: "What's the matter? / should",
          titleZh: "询问状况与提出建议",
          pattern: "What's the matter? — I have a + 症状.   You should / shouldn't + 动词原形.",
          notes: [
            "have a headache / a fever / a sore throat 是固定说法。",
            "should 表示建议，不是强制命令。",
            "否定：You shouldn't run today.",
          ],
          examples: [
            { en: "What's the matter? — I have a headache and a sore throat.", zh: "怎么了？——我头疼，嗓子也疼。" },
            { en: "You should drink warm water. You shouldn't run today.", zh: "你应该喝温水。今天不该跑步。" },
            { en: "He should rest and lie down.", zh: "他应该休息并躺下。" },
          ],
        },
        reading: {
          title: "A Quiet Twenty Minutes",
          titleZh: "安静的二十分钟",
          text: "Tom does not look well on Tuesday. \"What's the matter?\" Maya asks. He has a headache and a sore throat. He does not have a fever, but he feels tired.\n\nMs. Green says he should not run in PE. The nurse agrees. \"You should drink warm water. You shouldn't eat more ice cream today. Lie down for twenty minutes.\"\n\nTom rests. The room is quiet. He thinks about yesterday: too little sleep, too much junk food, and a long game on his phone.\n\nWhen he sits up, his head is a little better. \"I should go to bed earlier,\" he tells Maya. Pip nods. \"And I should stop hiding in cold boxes.\"",
          textZh:
            "星期二汤姆看起来不太舒服。“你怎么了？”玛雅问。他头疼，嗓子也疼。他没有发烧，但觉得很累。\n\n格林老师说他不该在体育课跑步。校医也同意。“你应该喝温水。今天不该再吃冰淇淋。躺二十分钟。”\n\n汤姆休息着。房间很安静。他想起昨天：睡得太少，垃圾食品太多，手机游戏时间太长。\n\n他坐起来时，头好了一点。“我应该早点睡觉，”他告诉玛雅。皮普点点头：“我也该别再躲进冷箱子里。”",
        },
        practice: [
          { type: "choice", q: "What's the matter with Tom?", options: ["He has a headache and a sore throat.", "He has a broken leg.", "He has a fever and a cough only."], answer: 0 },
          { type: "choice", q: "You shouldn't run. 表示：", options: ["你必须跑", "你不该跑", "你会跑吗"], answer: 1 },
          { type: "fill", q: "You _____ drink warm water and rest.", answer: "should", hint: "应该" },
          { type: "order", words: ["the", "What's", "matter", "?"], answer: "What's the matter?" },
          { type: "tf", q: "The nurse tells Tom to eat more ice cream today.", answer: false },
          { type: "listen", audio: "You should drink warm water.", options: ["You should drink warm water.", "You should run in PE today.", "You should eat more ice cream."], answer: 0 },
        ],
        fun: {
          title: "Feel better",
          titleZh: "好起来",
          chant: [
            "Headache, fever, sore throat too,",
            "What's the matter? Here's what to do:",
            "You should rest. You shouldn't race.",
            "Warm water, quiet, a slower pace.",
          ],
        },
      },

      {
        id: 10,
        title: "Could You Please Help?",
        titleZh: "你能帮个忙吗？",
        theme: "chores",
        color: "#8b6914",
        emoji: "🧹",
        goals: [
          "用 Could you please ...? 礼貌提出请求",
          "谈论家务和分担",
          "读一篇周末家务故事",
        ],
        dialogue: {
          title: "Sunday at Home",
          titleZh: "星期天在家",
          scene: "Lily's mum is busy. The living room is a mess.",
          sceneZh: "莉莉的妈妈很忙。客厅很乱。",
          lines: [
            { speaker: "Mum", text: "Lily, could you please take out the rubbish?", zh: "莉莉，能请你把垃圾倒掉吗？" },
            { speaker: "Lily", text: "Sure. Could I do it after I finish this page?", zh: "当然。我写完这一页再去，可以吗？" },
            { speaker: "Mum", text: "Yes. And could you please fold the clothes? I have to go out.", zh: "可以。还能请你把衣服叠好吗？我得出门。" },
            { speaker: "Tom", text: "I can help. I'll do the dishes.", zh: "我能帮忙。我来洗碗。" },
            { speaker: "Ben", text: "Could you please not play music so loudly? I'm doing homework.", zh: "能请你别把音乐放这么响吗？我在写作业。" },
            { speaker: "Pip", text: "Could I please keep this sock? It is a perfect bed.", zh: "我能留下这只袜子吗？它是完美的床。" },
            { speaker: "Lily", text: "No, Pip. Give it back. We should share the work, not the socks.", zh: "不行，皮普。还回去。我们该分担家务，不是分担袜子。" },
          ],
        },
        vocab: [
          { en: "rubbish", ipa: "/ˈrʌbɪʃ/", zh: "垃圾", example: "Could you please take out the rubbish?", exampleZh: "能请你把垃圾倒掉吗？" },
          { en: "fold", ipa: "/fəʊld/", zh: "折叠", example: "Please fold the clothes.", exampleZh: "请把衣服叠好。" },
          { en: "dishes", ipa: "/ˈdɪʃɪz/", zh: "餐具", example: "Tom will do the dishes.", exampleZh: "汤姆来洗碗。" },
          { en: "chore", ipa: "/tʃɔː(r)/", zh: "杂务；家务事", example: "Everyone has a chore on Sunday.", exampleZh: "星期天每个人都有一件家务。" },
          { en: "sweep", ipa: "/swiːp/", zh: "扫", example: "Could you sweep the floor?", exampleZh: "你能扫扫地吗？" },
          { en: "hate", ipa: "/heɪt/", zh: "讨厌", example: "Ben hates doing the dishes, but he still helps.", exampleZh: "本讨厌洗碗，但他还是帮忙。" },
          { en: "lend", ipa: "/lend/", zh: "借出", example: "Could you lend me your dictionary?", exampleZh: "能把词典借我吗？" },
          { en: "fair", ipa: "/feə(r)/", zh: "公平的", example: "Sharing chores is fair.", exampleZh: "分担家务是公平的。" },
        ],
        grammar: {
          title: "Could you please ...?",
          titleZh: "礼貌请求",
          pattern: "Could you please + 动词原形? — Sure. / Sorry, I have to ...",
          notes: [
            "Could you please ...? 比 Can you ...? 更客气。",
            "Could you please not + 动词：请不要……",
            "have to 表示客观需要：I have to go out.",
          ],
          examples: [
            { en: "Could you please take out the rubbish? — Sure.", zh: "能请你把垃圾倒掉吗？——当然。" },
            { en: "Could you please not play music so loudly?", zh: "能请你别把音乐放这么响吗？" },
            { en: "I have to go out. Could you fold the clothes?", zh: "我得出门。你能把衣服叠好吗？" },
          ],
        },
        reading: {
          title: "A Fair Sunday",
          titleZh: "公平的星期天",
          text: "Sunday morning is chore time at Lily's home. Mum has to visit grandma. \"Could you please take out the rubbish and fold the clothes?\" she asks. Lily says yes, but she wants to finish one page of homework first.\n\nTom comes over. He does not hate chores as much as he says. He does the dishes and sweeps the floor. Ben works at the table. \"Could you please not play music so loudly?\" he asks. Tom turns it down.\n\nPip tries to lend a sock a new job as a bed. Lily takes it back. \"Sharing work is fair,\" she says. \"Keeping socks is not.\"\n\nWhen Mum comes home, the living room is clear. \"Thank you,\" she says. \"Could we please have tea now?\"",
          textZh:
            "星期天早上是莉莉家的家务时间。妈妈得去看奶奶。“能请你倒掉垃圾并叠好衣服吗？”她问。莉莉答应了，但想先写完一页作业。\n\n汤姆过来了。他并不像嘴里说的那么讨厌家务。他洗碗、扫地。本在桌边学习。“能请你别把音乐放这么响吗？”他问。汤姆把音量关小了。\n\n皮普想把一只袜子改造成床。莉莉把它拿了回来。“分担家务是公平的，”她说，“私藏袜子不公平。”\n\n妈妈回家时，客厅已经整齐。“谢谢你们，”她说，“现在能请大家喝杯茶吗？”",
        },
        practice: [
          { type: "choice", q: "What does Mum ask Lily to do first?", options: ["Play music loudly.", "Take out the rubbish.", "Lend Pip a sock."], answer: 1 },
          { type: "choice", q: "Could you please ...? 主要用来：", options: ["下命令", "礼貌请求", "谈论过去"], answer: 1 },
          { type: "fill", q: "Could you please take _____ the rubbish?", answer: "out", hint: "倒掉" },
          { type: "order", words: ["you", "Could", "please", "help", "?"], answer: "Could you please help?" },
          { type: "tf", q: "Sharing chores is fair.", answer: true },
          { type: "listen", audio: "Could you please take out the rubbish?", options: ["Could you please take out the rubbish?", "Could you please eat the rubbish?", "Could you please hide the clothes?"], answer: 0 },
        ],
        fun: {
          title: "Please and help",
          titleZh: "请与帮",
          chant: [
            "Could you please sweep? Could you please fold?",
            "Could you please help before the day is old?",
            "I have to go. You have to try.",
            "Fair work, kind words — that's our Sunday sky.",
          ],
        },
      },

      {
        id: 11,
        title: "What Were You Doing?",
        titleZh: "你当时在做什么？",
        theme: "past-continuous",
        color: "#3d6b8a",
        emoji: "🌧️",
        goals: [
          "用过去进行时描述某个时刻正在发生的事",
          "搭配 when / while 讲故事",
          "读一篇暴风雨夜的短文",
        ],
        dialogue: {
          title: "The Rainstorm",
          titleZh: "那场暴雨",
          scene: "Wednesday. The class talks about last night's storm.",
          sceneZh: "星期三。全班在谈论昨晚的暴风雨。",
          lines: [
            { speaker: "Ms. Green", text: "What were you doing when the rainstorm came?", zh: "暴风雨来的时候，你在做什么？" },
            { speaker: "Lily", text: "I was doing my homework. The lights went out at eight.", zh: "我在写作业。八点灯灭了。" },
            { speaker: "Tom", text: "I was playing football outside. We ran home quickly.", zh: "我在外面踢足球。我们很快跑回了家。" },
            { speaker: "Maya", text: "I was reading by the window while the wind was hitting the glass.", zh: "风拍打玻璃的时候，我在窗边看书。" },
            { speaker: "Ben", text: "I was helping my dad. We were looking for candles.", zh: "我在帮爸爸。我们在找蜡烛。" },
            { speaker: "Pip", text: "I was sleeping under the sofa. Storms are loud.", zh: "我在沙发底下睡觉。暴风雨很吵。" },
            { speaker: "Ms. Green", text: "While you were waiting, the town workers were fixing the lines.", zh: "你们等待的时候，镇上的工人在修线路。" },
          ],
        },
        vocab: [
          { en: "rainstorm", ipa: "/ˈreɪnstɔːm/", zh: "暴风雨", example: "What were you doing when the rainstorm came?", exampleZh: "暴风雨来的时候你在做什么？" },
          { en: "while", ipa: "/waɪl/", zh: "当……的时候", example: "While the wind was hitting the glass, Maya was reading.", exampleZh: "风拍打玻璃的时候，玛雅在看书。" },
          { en: "suddenly", ipa: "/ˈsʌdənli/", zh: "突然", example: "Suddenly the lights went out.", exampleZh: "灯突然灭了。" },
          { en: "against", ipa: "/əˈɡenst/", zh: "靠着；顶着", example: "The wind was hitting against the window.", exampleZh: "风正拍打着窗户。" },
          { en: "fall", ipa: "/fɔːl/", zh: "倒下；落下", example: "A small tree fell in the park.", exampleZh: "公园里一棵小树倒下了。" },
          { en: "report", ipa: "/rɪˈpɔːt/", zh: "报道；报告", example: "The news reported a strong storm.", exampleZh: "新闻报道了一场强风暴。" },
          { en: "rise", ipa: "/raɪz/", zh: "上升", example: "The river was rising all night.", exampleZh: "河水整夜都在上涨。" },
          { en: "asleep", ipa: "/əˈsliːp/", zh: "睡着的", example: "Pip was asleep under the sofa.", exampleZh: "皮普在沙发底下睡着了。" },
        ],
        grammar: {
          title: "was / were + doing",
          titleZh: "过去进行时",
          pattern: "What were you doing when ...? — I was + 动词-ing.",
          notes: [
            "过去进行时表示过去某时刻或某段时间正在发生的动作。",
            "I / he / she / it 用 was；you / we / they 用 were。",
            "when 常接短暂动作，while 常接持续动作。",
          ],
          examples: [
            { en: "What were you doing when the rainstorm came? — I was doing homework.", zh: "暴风雨来时你在做什么？——我在写作业。" },
            { en: "While the wind was hitting the glass, Maya was reading.", zh: "风拍打玻璃时，玛雅在看书。" },
            { en: "They were looking for candles when the lights went out.", zh: "灯灭的时候，他们正在找蜡烛。" },
          ],
        },
        reading: {
          title: "Lights Out at Eight",
          titleZh: "八点灯灭了",
          text: "The rainstorm came after dinner. Lily was doing her homework when the lights went out at eight. Suddenly the room was dark. She sat still and listened.\n\nTom was playing football when the first heavy rain began. The boys ran home. While they were running, a small tree fell in the park.\n\nMaya was reading by the window. The wind was hitting against the glass. Ben and his dad were looking for candles. Pip was already asleep under the sofa.\n\nThe news later reported that the river was rising, but the town was safe. In the morning, Class 8 wrote what they were doing. The storm became a story they could share.",
          textZh:
            "晚饭后暴风雨来了。莉莉正在写作业，八点灯灭了。房间突然变黑。她坐着不动，听着外面的声音。\n\n第一场大雨开始时，汤姆正在踢足球。男孩们跑回家。他们跑的时候，公园里一棵小树倒下了。\n\n玛雅在窗边看书。风正拍打着玻璃。本和爸爸在找蜡烛。皮普已经在沙发底下睡着了。\n\n后来新闻报道说河水在上涨，但小镇是安全的。早上，八班写下自己当时在做什么。那场风暴变成了他们可以分享的故事。",
        },
        practice: [
          { type: "choice", q: "What was Lily doing when the lights went out?", options: ["She was playing football.", "She was doing her homework.", "She was sleeping under the sofa."], answer: 1 },
          { type: "choice", q: "I was doing homework. 是：", options: ["一般现在时", "过去进行时", "现在完成时"], answer: 1 },
          { type: "fill", q: "What _____ you doing when the rainstorm came?", answer: "were", hint: "you 后面的 be" },
          { type: "order", words: ["were", "What", "you", "doing", "?"], answer: "What were you doing?" },
          { type: "tf", q: "Pip was asleep under the sofa during the storm.", answer: true },
          { type: "listen", audio: "I was doing my homework.", options: ["I was doing my homework.", "I was eating ice cream outside.", "I was flying a plane."], answer: 0 },
        ],
        fun: {
          title: "When the storm came",
          titleZh: "风暴来时",
          chant: [
            "What were you doing? What did you see?",
            "I was reading. You were running with me.",
            "When the lights went out, we were waiting inside.",
            "While the rain was falling, we sat side by side.",
          ],
        },
      },

      {
        id: 12,
        title: "Have You Ever Been There?",
        titleZh: "你去过那里吗？",
        theme: "review",
        color: "#2c6e6a",
        emoji: "🗺️",
        goals: [
          "用现在完成时谈论经历",
          "复习本册主要时态和句型",
          "读一封介绍自己的邮件并试着写回信",
        ],
        dialogue: {
          title: "A Year of Stories",
          titleZh: "一年的故事",
          scene: "The last English class of the book. Sunshine on the desks.",
          sceneZh: "这本书的最后一节英语课。阳光照在课桌上。",
          lines: [
            { speaker: "Ms. Green", text: "Have you ever been to a museum this year?", zh: "今年你去过博物馆吗？" },
            { speaker: "Lily", text: "Yes, I have. I went to the ship museum in Qingdao.", zh: "去过。我去了青岛的船舶博物馆。" },
            { speaker: "Tom", text: "I haven't been to a museum, but I have been to the new park many times.", zh: "我没去过博物馆，但我去过新公园很多次。" },
            { speaker: "Maya", text: "I have never been to another country, but I have read many news stories.", zh: "我从未去过别的国家，但我读过很多新闻。" },
            { speaker: "Ben", text: "I have already started a small app. I haven't finished it yet.", zh: "我已经开始做一个小应用。我还没做完。" },
            { speaker: "Pip", text: "Have you ever been in a suitcase? I have. Once is enough!", zh: "你坐过行李箱吗？我坐过。一次就够了！" },
            { speaker: "Ms. Green", text: "Good. Now read Maya's email. Then write about places you have been and things you will do.", zh: "很好。现在读玛雅的邮件，然后写下你去过的地方和将要做的事。" },
          ],
        },
        vocab: [
          { en: "ever", ipa: "/ˈevə(r)/", zh: "曾经（用于疑问）", example: "Have you ever been to a museum?", exampleZh: "你去过博物馆吗？" },
          { en: "never", ipa: "/ˈnevə(r)/", zh: "从未", example: "I have never been to another country.", exampleZh: "我从未去过别的国家。" },
          { en: "already", ipa: "/ɔːlˈredi/", zh: "已经", example: "I have already started a small app.", exampleZh: "我已经开始做一个小应用。" },
          { en: "yet", ipa: "/jet/", zh: "还（用于否定/疑问）", example: "I haven't finished it yet.", exampleZh: "我还没做完。" },
          { en: "been", ipa: "/biːn/", zh: "去过（be 的过去分词）", example: "I have been to the new park many times.", exampleZh: "我去过新公园很多次。" },
          { en: "amusement park", ipa: "/əˈmjuːzmənt pɑːk/", zh: "游乐场", example: "Have you ever been to an amusement park?", exampleZh: "你去过游乐场吗？" },
          { en: "twice", ipa: "/twaɪs/", zh: "两次", example: "She has seen that film twice.", exampleZh: "那部电影她看过两次。" },
          { en: "email", ipa: "/ˈiːmeɪl/", zh: "电子邮件", example: "Maya writes an email to a friend.", exampleZh: "玛雅给朋友写一封邮件。" },
        ],
        grammar: {
          title: "Have you ever ...?",
          titleZh: "现在完成时：谈论经历",
          pattern: "Have / Has + 主语 + 过去分词? — Yes, I have. / No, I haven't. I have never ...",
          notes: [
            "现在完成时：have / has + 过去分词，强调经历或结果。",
            "ever 用于问句，never 用于否定：Have you ever ...? I have never ...",
            "already 多用于肯定，yet 多用于否定和疑问。本册也复习了过去时、will 和 be going to。",
          ],
          examples: [
            { en: "Have you ever been to a museum? — Yes, I have.", zh: "你去过博物馆吗？——去过。" },
            { en: "I have never been to another country.", zh: "我从未去过别的国家。" },
            { en: "I have already started. I haven't finished yet.", zh: "我已经开始了。我还没完成。" },
          ],
        },
        reading: {
          title: "Maya's Email",
          titleZh: "玛雅的邮件",
          text: "Dear Sam,\n\nHow's it going? My name is Maya. I am fourteen. I am quieter than my friend Lily, but I am hard-working.\n\nHave you ever been to our town? I have been to the ship museum in Qingdao, and I have been to Green Park many times. I have never been to another country yet.\n\nLast summer Lily went to the sea. I visited my grandma in the countryside. When the rainstorm came this term, I was reading by the window.\n\nI exercise twice a week. I want to be a journalist. I am going to ask better questions. I believe people will still need kind news.\n\nWhat's the matter if I feel tired? I should rest, then try again. Could you please write back? Tell me where you have been, and what you are going to do.\n\nYour friend,\nMaya",
          textZh:
            "亲爱的山姆：\n\n最近怎么样？我叫玛雅。我十四岁。我比朋友莉莉文静，但我很勤奋。\n\n你来过我们小镇吗？我去过青岛的船舶博物馆，也去过绿园很多次。我还从未去过别的国家。\n\n去年夏天莉莉去了海边。我去乡下看望了奶奶。这学期暴风雨来的时候，我正在窗边看书。\n\n我一周锻炼两次。我想当记者。我打算提出更好的问题。我相信人们仍然需要善良的新闻。\n\n如果我觉得累了，该怎么办？我应该休息，然后再试。能请你回信吗？告诉我你去过哪里，以及你打算做什么。\n\n你的朋友\n玛雅",
        },
        practice: [
          { type: "choice", q: "Has Maya been to another country?", options: ["Yes, she has been twice.", "No, she has never been to another country.", "Yes, she lives there now."], answer: 1 },
          { type: "choice", q: "Have you ever been ...? 用的是：", options: ["一般过去时", "现在完成时", "过去进行时"], answer: 1 },
          { type: "fill", q: "I haven't finished the app _____.", answer: "yet", hint: "还" },
          { type: "order", words: ["you", "Have", "ever", "been", "there", "?"], answer: "Have you ever been there?" },
          { type: "tf", q: "Maya wants Sam to write back about places and plans.", answer: true },
          { type: "listen", audio: "Have you ever been to a museum?", options: ["Have you ever been to a museum?", "Have you ever eaten the museum?", "Have you ever closed the blender?"], answer: 0 },
        ],
        fun: {
          title: "Write your email",
          titleZh: "写下你的邮件",
          chant: [
            "Have you ever tried? Have you ever been?",
            "I have already started. I'll try again.",
            "I went, I was doing, I'm going to, I will —",
            "Twelve units later, I can tell my story still.",
            "Please write back. I will wait.",
            "Sunshine English — Grade Eight. That's great!",
          ],
        },
      },
    ],
  };
});
