/* Sunshine English · Grade 5 — original classroom content */
(function (root, factory) {
  const data = factory();
  if (typeof module === "object" && module.exports) module.exports = data;
  root.TEXTBOOK = data;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  return {
    meta: {
      title: "Sunshine English",
      titleZh: "阳光英语",
      grade: "五年级",
      volume: "全一册",
      mascot: "Pip",
      mascotZh: "小狐皮普",
      blurb:
        "给小学五年级同学的互动英语课本。跟着皮普认识新朋友，学说、认词、读短文，再做一做练习。",
    },

    letters: [
      { letter: "A", word: "apple", zh: "苹果", emoji: "🍎", ipa: "/æ/" },
      { letter: "B", word: "ball", zh: "球", emoji: "⚽", ipa: "/b/" },
      { letter: "C", word: "cat", zh: "猫", emoji: "🐱", ipa: "/k/" },
      { letter: "D", word: "dog", zh: "狗", emoji: "🐶", ipa: "/d/" },
      { letter: "E", word: "egg", zh: "鸡蛋", emoji: "🥚", ipa: "/e/" },
      { letter: "F", word: "fish", zh: "鱼", emoji: "🐟", ipa: "/f/" },
      { letter: "G", word: "grape", zh: "葡萄", emoji: "🍇", ipa: "/g/" },
      { letter: "H", word: "hat", zh: "帽子", emoji: "🎩", ipa: "/h/" },
      { letter: "I", word: "ice cream", zh: "冰淇淋", emoji: "🍦", ipa: "/aɪ/" },
      { letter: "J", word: "juice", zh: "果汁", emoji: "🧃", ipa: "/dʒ/" },
      { letter: "K", word: "kite", zh: "风筝", emoji: "🪁", ipa: "/k/" },
      { letter: "L", word: "lion", zh: "狮子", emoji: "🦁", ipa: "/l/" },
      { letter: "M", word: "moon", zh: "月亮", emoji: "🌙", ipa: "/m/" },
      { letter: "N", word: "nose", zh: "鼻子", emoji: "👃", ipa: "/n/" },
      { letter: "O", word: "orange", zh: "橙子", emoji: "🍊", ipa: "/ɒ/" },
      { letter: "P", word: "Pip", zh: "皮普", emoji: "🦊", ipa: "/p/" },
      { letter: "Q", word: "queen", zh: "女王", emoji: "👑", ipa: "/kw/" },
      { letter: "R", word: "rabbit", zh: "兔子", emoji: "🐰", ipa: "/r/" },
      { letter: "S", word: "sun", zh: "太阳", emoji: "☀️", ipa: "/s/" },
      { letter: "T", word: "tree", zh: "树", emoji: "🌳", ipa: "/t/" },
      { letter: "U", word: "umbrella", zh: "雨伞", emoji: "☂️", ipa: "/ʌ/" },
      { letter: "V", word: "violin", zh: "小提琴", emoji: "🎻", ipa: "/v/" },
      { letter: "W", word: "water", zh: "水", emoji: "💧", ipa: "/w/" },
      { letter: "X", word: "x-ray", zh: "X 光", emoji: "🩻", ipa: "/eks/" },
      { letter: "Y", word: "yo-yo", zh: "悠悠球", emoji: "🪀", ipa: "/j/" },
      { letter: "Z", word: "zebra", zh: "斑马", emoji: "🦓", ipa: "/z/" },
    ],

    units: [
      {
        id: 1,
        title: "What's He Like?",
        titleZh: "他是什么样的人？",
        theme: "friends",
        color: "#3d7ec9",
        emoji: "😊",
        goals: [
          "用形容词描述同学和老师",
          "问答：What's he/she like?",
          "听读一段介绍新老师的对话",
        ],
        dialogue: {
          title: "A New Teacher",
          titleZh: "新来的老师",
          scene: "Monday morning. Lily and Tom meet in the school hall.",
          sceneZh: "星期一早上，莉莉和汤姆在学校大厅遇见。",
          lines: [
            { speaker: "Lily", text: "Hi, Tom! Do you know our new art teacher?", zh: "嗨，汤姆！你认识我们新来的美术老师吗？" },
            { speaker: "Tom", text: "Not yet. What's she like?", zh: "还不认识。她是什么样的人？" },
            { speaker: "Lily", text: "She's kind and funny. She tells jokes in class!", zh: "她很亲切，也很有趣。她上课会讲笑话！" },
            { speaker: "Tom", text: "Cool! Is she strict?", zh: "真棒！她严格吗？" },
            { speaker: "Lily", text: "A little. She wants us to work hard, but she is helpful.", zh: "有一点。她希望我们努力学习，但她很乐于助人。" },
            { speaker: "Tom", text: "What about Mr. Brown? What's he like?", zh: "那布朗老师呢？他是什么样的人？" },
            { speaker: "Lily", text: "He's old and clever. He knows many stories.", zh: "他年纪大，也很聪明。他知道很多故事。" },
            { speaker: "Tom", text: "I like clever teachers. Let's say hello after class.", zh: "我喜欢聪明的老师。下课我们去打个招呼吧。" },
          ],
        },
        vocab: [
          { en: "kind", ipa: "/kaɪnd/", zh: "亲切的；善良的", example: "Ms. Green is kind to every student.", exampleZh: "格林老师对每个学生都很亲切。" },
          { en: "funny", ipa: "/ˈfʌni/", zh: "有趣的；滑稽的", example: "Tom is funny. He makes us laugh.", exampleZh: "汤姆很有趣，他让我们发笑。" },
          { en: "strict", ipa: "/strɪkt/", zh: "严格的", example: "Our PE teacher is strict but fair.", exampleZh: "我们的体育老师很严格，但很公平。" },
          { en: "helpful", ipa: "/ˈhelpfl/", zh: "乐于助人的", example: "Maya is helpful. She carries the books.", exampleZh: "玛雅很乐于助人。她帮忙搬书。" },
          { en: "clever", ipa: "/ˈklevə(r)/", zh: "聪明的", example: "Ben is clever at maths.", exampleZh: "本数学很聪明。" },
          { en: "polite", ipa: "/pəˈlaɪt/", zh: "有礼貌的", example: "Please be polite to visitors.", exampleZh: "请对来访者有礼貌。" },
          { en: "shy", ipa: "/ʃaɪ/", zh: "害羞的", example: "Pip is shy with new friends.", exampleZh: "皮普见到新朋友会害羞。" },
          { en: "hard-working", ipa: "/ˌhɑːd ˈwɜːkɪŋ/", zh: "勤奋的", example: "Lily is hard-working. She reads every night.", exampleZh: "莉莉很勤奋。她每天晚上都读书。" },
        ],
        grammar: {
          title: "What's he like?",
          titleZh: "询问外貌或性格",
          pattern: "What's he / she like? — He / She is + 形容词.",
          notes: [
            "like 在这里不是“喜欢”，而是“什么样”。",
            "回答时用 is + 形容词，可以一次说两个词：kind and funny。",
            "问许多人用 What are they like?",
          ],
          examples: [
            { en: "What's your mum like? — She's kind and hard-working.", zh: "你妈妈是什么样的人？——她善良又勤奋。" },
            { en: "What's Mr. Brown like? — He's old and clever.", zh: "布朗老师是什么样的人？——他年长又聪明。" },
            { en: "What are the twins like? — They're shy but polite.", zh: "那对双胞胎是什么样的人？——他们害羞但有礼貌。" },
          ],
        },
        reading: {
          title: "My Best Friend",
          titleZh: "我最好的朋友",
          text: "My best friend is Maya. She is ten years old. Maya is kind and helpful. When I forget my pencil, she always has one for me.\n\nMaya is a little shy in a big group, but she is funny with me. She tells quiet jokes and draws clever cartoons.\n\nOur teacher, Ms. Green, is strict in class. She wants us to listen. After class she is kind. Maya and I like her very much.\n\nI am happy I have a friend like Maya.",
          textZh:
            "我最好的朋友是玛雅。她十岁。玛雅善良又乐于助人。我忘带铅笔时，她总有一支给我。\n\n玛雅在人多时有点害羞，但和我在一起时很有趣。她会轻轻讲笑话，还会画很巧妙的漫画。\n\n我们的老师格林老师上课很严格，希望我们认真听。下课后她很亲切。玛雅和我都很喜欢她。\n\n有玛雅这样的朋友，我很开心。",
        },
        practice: [
          { type: "choice", q: "What's Maya like?", options: ["She is kind and helpful.", "She is old and strict.", "She is noisy and tall."], answer: 0 },
          { type: "choice", q: "“What's he like?” 问的是：", options: ["他喜欢什么？", "他是什么样的人？", "他在哪里？"], answer: 1 },
          { type: "fill", q: "Ms. Green is s_____ in class, but she is kind after class.", answer: "strict", hint: "严格的" },
          { type: "order", words: ["like", "What's", "she", "?"], answer: "What's she like?" },
          { type: "tf", q: "Maya is funny with her best friend.", answer: true },
          { type: "listen", audio: "He is polite and hard-working.", options: ["He is polite and hard-working.", "He is shy and funny.", "He is old and strict."], answer: 0 },
        ],
        fun: {
          title: "Say it with Pip",
          titleZh: "跟着皮普说",
          chant: [
            "Kind, kind, she is kind.",
            "Funny, funny, he is funny.",
            "Helpful friends are on my mind.",
            "What's he like? What's she like?",
            "Hard-working, clever, polite!",
          ],
        },
      },

      {
        id: 2,
        title: "My Week",
        titleZh: "我的一周",
        theme: "week",
        color: "#2f9e6b",
        emoji: "📅",
        goals: [
          "说出一周七天的活动",
          "问答：What do you do on Mondays?",
          "用 on + 星期 谈论习惯",
        ],
        dialogue: {
          title: "A Busy Week",
          titleZh: "忙碌的一周",
          scene: "Friday afternoon. Ben shows Lily his notebook.",
          sceneZh: "星期五下午，本把笔记本给莉莉看。",
          lines: [
            { speaker: "Lily", text: "Ben, what do you do on Mondays?", zh: "本，你星期一做什么？" },
            { speaker: "Ben", text: "I have music class. I play the piano.", zh: "我上音乐课。我弹钢琴。" },
            { speaker: "Lily", text: "What about Tuesdays?", zh: "那星期二呢？" },
            { speaker: "Ben", text: "I do my homework and read a book.", zh: "我写作业，再读一本书。" },
            { speaker: "Lily", text: "On Wednesdays I play football with Tom.", zh: "星期三我和汤姆踢足球。" },
            { speaker: "Ben", text: "Nice! I go shopping with my mum on Thursdays.", zh: "真好！星期四我和妈妈去购物。" },
            { speaker: "Lily", text: "On Saturdays we have a picnic in the park.", zh: "星期六我们在公园野餐。" },
            { speaker: "Ben", text: "Sundays are quiet. I clean my room and watch a film.", zh: "星期天很安静。我打扫房间，再看一部电影。" },
          ],
        },
        vocab: [
          { en: "Monday", ipa: "/ˈmʌndeɪ/", zh: "星期一", example: "We have English on Mondays.", exampleZh: "我们星期一上英语课。" },
          { en: "Wednesday", ipa: "/ˈwenzdeɪ/", zh: "星期三", example: "Football is on Wednesday.", exampleZh: "足球在星期三。" },
          { en: "Friday", ipa: "/ˈfraɪdeɪ/", zh: "星期五", example: "Friday is my favourite day.", exampleZh: "星期五是我最喜欢的一天。" },
          { en: "weekend", ipa: "/ˌwiːkˈend/", zh: "周末", example: "I visit my grandma at the weekend.", exampleZh: "我周末去看奶奶。" },
          { en: "do homework", ipa: "/duː ˈhəʊmwɜːk/", zh: "做家庭作业", example: "I do my homework after dinner.", exampleZh: "我晚饭后写作业。" },
          { en: "play football", ipa: "/pleɪ ˈfʊtbɔːl/", zh: "踢足球", example: "They play football on Wednesdays.", exampleZh: "他们星期三踢足球。" },
          { en: "go shopping", ipa: "/ɡəʊ ˈʃɒpɪŋ/", zh: "去购物", example: "Mum and I go shopping on Thursdays.", exampleZh: "妈妈和我星期四去购物。" },
          { en: "have a picnic", ipa: "/hæv ə ˈpɪknɪk/", zh: "去野餐", example: "We have a picnic on Saturdays.", exampleZh: "我们星期六去野餐。" },
        ],
        grammar: {
          title: "What do you do on Mondays?",
          titleZh: "询问一周的活动",
          pattern: "What do you do on + 星期? — I + 动词原形 ...",
          notes: [
            "星期前用 on：on Monday, on Fridays。",
            "谈习惯用一般现在时：I play / I go / I have。",
            "he / she 要加 -s：He plays football on Sundays.",
          ],
          examples: [
            { en: "What do you do on Tuesdays? — I read and do homework.", zh: "你星期二做什么？——我读书、写作业。" },
            { en: "What does Ben do on Mondays? — He has music class.", zh: "本星期一做什么？——他上音乐课。" },
            { en: "We have a picnic on Saturdays.", zh: "我们星期六去野餐。" },
          ],
        },
        reading: {
          title: "Tom's Week",
          titleZh: "汤姆的一周",
          text: "Tom is a busy boy. On Mondays he has English and art. On Tuesdays he does homework and helps his dad in the kitchen.\n\nWednesday is sports day. Tom plays football with Lily and Ben. On Thursdays he goes to the library. He likes quiet books.\n\nFriday is film night at home. On Saturday the family has a picnic if the sun is out. Sunday is for a clean room and a slow walk with Pip.\n\n\"I like my week,\" Tom says. \"Every day has a little fun.\"",
          textZh:
            "汤姆是个忙碌的男孩。星期一他有英语和美术。星期二他写作业，还在厨房帮爸爸。\n\n星期三是运动日。汤姆和莉莉、本一起踢足球。星期四他去图书馆，他喜欢安静的书。\n\n星期五是家里的电影夜。星期六如果出太阳，全家人就去野餐。星期天用来把房间打扫干净，再和皮普慢慢散步。\n\n“我喜欢我的一周，”汤姆说，“每天都有一点点快乐。”",
        },
        practice: [
          { type: "choice", q: "What does Tom do on Wednesdays?", options: ["He goes shopping.", "He plays football.", "He watches a film."], answer: 1 },
          { type: "choice", q: "星期前常用哪个词？", options: ["in", "on", "at"], answer: 1 },
          { type: "fill", q: "I _____ my homework after dinner.", answer: "do", hint: "做（作业）" },
          { type: "order", words: ["do", "What", "you", "on", "Mondays", "?"], answer: "What do you do on Mondays?" },
          { type: "tf", q: "Tom plays football on Sundays.", answer: false },
          { type: "listen", audio: "We have a picnic on Saturdays.", options: ["We have a picnic on Saturdays.", "We go shopping on Sundays.", "We play football on Fridays."], answer: 0 },
        ],
        fun: {
          title: "Days of the week",
          titleZh: "星期歌",
          chant: [
            "Monday, Tuesday, I read a book.",
            "Wednesday, football — come and look!",
            "Thursday shopping, Friday film,",
            "Saturday picnic, Sunday still.",
            "That's my week. How about you?",
          ],
        },
      },

      {
        id: 3,
        title: "What Would You Like?",
        titleZh: "你想要什么？",
        theme: "food",
        color: "#e07a3d",
        emoji: "🍜",
        goals: [
          "点餐和招待客人",
          "使用 I'd like ...",
          "认识常见食物和饮料",
        ],
        dialogue: {
          title: "At the School Party",
          titleZh: "在学校联欢会上",
          scene: "The class party. Ms. Green stands by the food table.",
          sceneZh: "班级联欢会。格林老师站在食物桌旁。",
          lines: [
            { speaker: "Ms. Green", text: "Welcome! What would you like, Lily?", zh: "欢迎！莉莉，你想要什么？" },
            { speaker: "Lily", text: "I'd like a sandwich, please. And some juice.", zh: "我想要一个三明治，再来一点果汁。" },
            { speaker: "Ms. Green", text: "Here you are. Tom, what would you like?", zh: "给你。汤姆，你想要什么？" },
            { speaker: "Tom", text: "I'd like noodles and a salad.", zh: "我想要面条和一份沙拉。" },
            { speaker: "Ben", text: "I'd like a hamburger and ice cream!", zh: "我想要汉堡和冰淇淋！" },
            { speaker: "Ms. Green", text: "Ice cream after the hamburger, please.", zh: "请先吃汉堡，再吃冰淇淋。" },
            { speaker: "Maya", text: "I'd like dumplings and tea. Thank you.", zh: "我想要饺子和茶。谢谢。" },
            { speaker: "Pip", text: "I'd like a little sandwich too. Please!", zh: "我也想要一小块三明治。拜托！" },
          ],
        },
        vocab: [
          { en: "sandwich", ipa: "/ˈsænwɪtʃ/", zh: "三明治", example: "I'd like a chicken sandwich.", exampleZh: "我想要一个鸡肉三明治。" },
          { en: "salad", ipa: "/ˈsæləd/", zh: "沙拉", example: "This salad is fresh and green.", exampleZh: "这份沙拉又新鲜又绿。" },
          { en: "hamburger", ipa: "/ˈhæmbɜːɡə(r)/", zh: "汉堡包", example: "Ben likes hamburgers.", exampleZh: "本喜欢汉堡包。" },
          { en: "noodles", ipa: "/ˈnuːdlz/", zh: "面条", example: "Tom would like noodles.", exampleZh: "汤姆想吃面条。" },
          { en: "dumplings", ipa: "/ˈdʌmplɪŋz/", zh: "饺子", example: "Maya would like dumplings and tea.", exampleZh: "玛雅想要饺子和茶。" },
          { en: "ice cream", ipa: "/ˈaɪs kriːm/", zh: "冰淇淋", example: "Ice cream is sweet and cold.", exampleZh: "冰淇淋又甜又凉。" },
          { en: "juice", ipa: "/dʒuːs/", zh: "果汁", example: "Apple juice, please.", exampleZh: "请来一杯苹果汁。" },
          { en: "I'd like", ipa: "/aɪd laɪk/", zh: "我想要（礼貌）", example: "I'd like some tea, please.", exampleZh: "我想要一点茶。" },
        ],
        grammar: {
          title: "What would you like?",
          titleZh: "礼貌地表达想要",
          pattern: "What would you like? — I'd like + 食物 / 饮料, please.",
          notes: [
            "I'd like = I would like，比 I want 更有礼貌。",
            "请人再加点用 Would you like some ...?",
            "不可数名词前常用 some：some juice, some tea。",
          ],
          examples: [
            { en: "What would you like? — I'd like a salad, please.", zh: "你想要什么？——我想要一份沙拉。" },
            { en: "Would you like some juice? — Yes, please.", zh: "你想来点果汁吗？——好的，谢谢。" },
            { en: "I'd like dumplings and tea.", zh: "我想要饺子和茶。" },
          ],
        },
        reading: {
          title: "Food for Friends",
          titleZh: "给朋友的食物",
          text: "Today is the class party. Ms. Green puts sandwiches, salad, noodles and dumplings on a long table. There is juice, tea and a small box of ice cream.\n\nLily would like a sandwich. Tom would like noodles. Maya would like dumplings because they taste like home. Ben would like a hamburger, and then ice cream.\n\nPip looks at the table. \"I'd like a little of everything,\" he says. Everyone laughs.\n\n\"Please say thank you,\" Ms. Green smiles. \"Food tastes better with polite words.\"",
          textZh:
            "今天是班级联欢会。格林老师把三明治、沙拉、面条和饺子放在长桌上。还有果汁、茶和一小盒冰淇淋。\n\n莉莉想要三明治。汤姆想要面条。玛雅想要饺子，因为那味道像家。本想要汉堡，然后再吃冰淇淋。\n\n皮普看着桌子说：“每一样我都想要一点点。”大家都笑了。\n\n“请说谢谢，”格林老师笑着说，“有礼貌的话，食物会更好吃。”",
        },
        practice: [
          { type: "choice", q: "A polite way to ask for food is:", options: ["Give me noodles!", "I'd like noodles, please.", "I take noodles now."], answer: 1 },
          { type: "choice", q: "Maya would like _____ because they taste like home.", options: ["hamburgers", "dumplings", "ice cream"], answer: 1 },
          { type: "fill", q: "_____ like some juice, please.", answer: "I'd", hint: "I would 的缩写" },
          { type: "order", words: ["would", "What", "you", "like", "?"], answer: "What would you like?" },
          { type: "tf", q: "I'd like is more polite than I want.", answer: true },
          { type: "listen", audio: "I'd like a sandwich and some juice.", options: ["I'd like a sandwich and some juice.", "I'd like ice cream and tea.", "I'd like dumplings and a hamburger."], answer: 0 },
        ],
        fun: {
          title: "Menu chant",
          titleZh: "菜单儿歌",
          chant: [
            "Sandwich, salad, noodles too,",
            "Dumplings, juice — how about you?",
            "I'd like this. I'd like that.",
            "Please and thank you. Tip your hat!",
          ],
        },
      },

      {
        id: 4,
        title: "What Can You Do?",
        titleZh: "你会做什么？",
        theme: "talent",
        color: "#7b5ea7",
        emoji: "🎨",
        goals: [
          "谈论能力：can / can't",
          "为才艺展示做自我介绍",
          "用 and / but 连接句子",
        ],
        dialogue: {
          title: "Talent Show",
          titleZh: "才艺展示",
          scene: "The children talk about the Friday talent show.",
          sceneZh: "孩子们在谈论星期五的才艺展示。",
          lines: [
            { speaker: "Ms. Green", text: "What can you do for the show, Lily?", zh: "莉莉，才艺展示你会做什么？" },
            { speaker: "Lily", text: "I can dance, and I can sing a little.", zh: "我会跳舞，也会唱一点点。" },
            { speaker: "Tom", text: "I can play football, but I can't dance!", zh: "我会踢足球，可是我不会跳舞！" },
            { speaker: "Maya", text: "I can draw cartoons. I can draw Pip!", zh: "我会画漫画。我能画出皮普！" },
            { speaker: "Ben", text: "I can do kung fu. Look! Hi-yah!", zh: "我会功夫。看！嗨呀！" },
            { speaker: "Pip", text: "I can jump and I can hide. I can't cook.", zh: "我会跳，也会躲。我不会做饭。" },
            { speaker: "Ms. Green", text: "Wonderful. We can all do something special.", zh: "太好了。我们每个人都能做特别的事。" },
            { speaker: "Lily", text: "Can you play the piano, Ms. Green?", zh: "格林老师，您会弹钢琴吗？" },
            { speaker: "Ms. Green", text: "Yes, I can. I'll play for the dancers.", zh: "会。我来给跳舞的同学伴奏。" },
          ],
        },
        vocab: [
          { en: "sing", ipa: "/sɪŋ/", zh: "唱歌", example: "Lily can sing a little.", exampleZh: "莉莉会唱一点点。" },
          { en: "dance", ipa: "/dɑːns/", zh: "跳舞", example: "She can dance very well.", exampleZh: "她跳舞跳得很好。" },
          { en: "draw cartoons", ipa: "/drɔː kɑːˈtuːnz/", zh: "画漫画", example: "Maya can draw cartoons.", exampleZh: "玛雅会画漫画。" },
          { en: "kung fu", ipa: "/ˌkʌŋ ˈfuː/", zh: "功夫", example: "Ben can do kung fu.", exampleZh: "本会功夫。" },
          { en: "swim", ipa: "/swɪm/", zh: "游泳", example: "Tom can swim in summer.", exampleZh: "汤姆夏天会游泳。" },
          { en: "cook", ipa: "/kʊk/", zh: "做饭", example: "Pip can't cook.", exampleZh: "皮普不会做饭。" },
          { en: "speak English", ipa: "/spiːk ˈɪŋɡlɪʃ/", zh: "说英语", example: "We can speak English in class.", exampleZh: "我们能在课堂上说英语。" },
          { en: "play the piano", ipa: "/pleɪ ðə piˈænəʊ/", zh: "弹钢琴", example: "Ms. Green can play the piano.", exampleZh: "格林老师会弹钢琴。" },
        ],
        grammar: {
          title: "can / can't",
          titleZh: "谈论能力",
          pattern: "What can you do? — I can + 动词原形. / I can't + 动词原形.",
          notes: [
            "can 后面用动词原形：can swim，不是 can swims。",
            "否定是 cannot 或 can't。",
            "问句把 can 提前：Can you dance? Yes, I can. / No, I can't.",
          ],
          examples: [
            { en: "What can you do? — I can draw cartoons.", zh: "你会做什么？——我会画漫画。" },
            { en: "Can Tom dance? — No, he can't. But he can play football.", zh: "汤姆会跳舞吗？——不会。但他会踢足球。" },
            { en: "We can speak English and we can sing.", zh: "我们会说英语，也会唱歌。" },
          ],
        },
        reading: {
          title: "We Can Do It",
          titleZh: "我们能做到",
          text: "Friday is the talent show. The hall is full of children and parents.\n\nLily can dance. Ms. Green can play the piano for her. Maya can draw a big cartoon of Pip on the board. Ben can do kung fu. He is careful and strong.\n\nTom can't dance, but he can tell a football story. Everyone claps.\n\nPip tries to cook a tiny cake. He can't. The cake is a little black. \"I can jump and I can laugh,\" Pip says. \"That's my show!\"\n\nMs. Green smiles. \"We can't do everything. But we can try, and we can be kind.\"",
          textZh:
            "星期五是才艺展示。大厅里坐满了孩子和家长。\n\n莉莉会跳舞。格林老师为她弹钢琴。玛雅能在黑板上画出大大的皮普漫画。本会功夫，他又小心又有力。\n\n汤姆不会跳舞，但他会讲一个足球故事。大家都鼓掌。\n\n皮普想做一块小蛋糕。他不会。蛋糕有点黑。“我会跳，也会笑，”皮普说，“那就是我的节目！”\n\n格林老师笑了：“我们不能什么都会。但我们可以试试，也可以彼此友善。”",
        },
        practice: [
          { type: "choice", q: "What can Maya do?", options: ["She can do kung fu.", "She can draw cartoons.", "She can cook a cake."], answer: 1 },
          { type: "choice", q: "can 后面的动词要用：", options: ["原形", "第三人称单数 -s", "过去式"], answer: 0 },
          { type: "fill", q: "Tom _____ dance, but he can play football.", answer: "can't", hint: "不会" },
          { type: "order", words: ["can", "What", "you", "do", "?"], answer: "What can you do?" },
          { type: "tf", q: "Pip can cook a perfect cake.", answer: false },
          { type: "listen", audio: "I can swim, but I can't cook.", options: ["I can swim, but I can't cook.", "I can dance and I can sing.", "I can play the piano."], answer: 0 },
        ],
        fun: {
          title: "Can you?",
          titleZh: "你会吗？",
          chant: [
            "I can sing. I can dance.",
            "I can try. I can chance.",
            "I can't fly. That's OK.",
            "I can learn a new thing today!",
          ],
        },
      },

      {
        id: 5,
        title: "There Is a Big Bed",
        titleZh: "有一张大床",
        theme: "home",
        color: "#c45c6a",
        emoji: "🏠",
        goals: [
          "用 there is / there are 描述房间",
          "认识家具和房间名称",
          "读一篇搬新家的短文",
        ],
        dialogue: {
          title: "Lily's New Room",
          titleZh: "莉莉的新房间",
          scene: "Lily opens the door. Maya and Pip come in.",
          sceneZh: "莉莉打开门。玛雅和皮普走进来。",
          lines: [
            { speaker: "Maya", text: "Wow! Your new home is nice.", zh: "哇！你的新家真漂亮。" },
            { speaker: "Lily", text: "Thanks. This is my bedroom. There is a big bed.", zh: "谢谢。这是我的卧室。有一张大床。" },
            { speaker: "Pip", text: "There is a plant by the window. I like it!", zh: "窗边有一盆植物。我喜欢！" },
            { speaker: "Maya", text: "Is there a closet?", zh: "有衣柜吗？" },
            { speaker: "Lily", text: "Yes, there is. My dresses are in the closet.", zh: "有。我的裙子在衣柜里。" },
            { speaker: "Maya", text: "What's in the living room?", zh: "客厅里有什么？" },
            { speaker: "Lily", text: "There is a sofa and a small table. There are two lamps.", zh: "有一张沙发和一张小桌子。还有两盏灯。" },
            { speaker: "Pip", text: "Is there any ice cream in the fridge?", zh: "冰箱里有冰淇淋吗？" },
            { speaker: "Lily", text: "There is juice. Come and see the kitchen!", zh: "有果汁。来看厨房吧！" },
          ],
        },
        vocab: [
          { en: "bedroom", ipa: "/ˈbedruːm/", zh: "卧室", example: "There is a big bed in my bedroom.", exampleZh: "我的卧室里有一张大床。" },
          { en: "living room", ipa: "/ˈlɪvɪŋ ruːm/", zh: "客厅", example: "We read in the living room.", exampleZh: "我们在客厅读书。" },
          { en: "kitchen", ipa: "/ˈkɪtʃɪn/", zh: "厨房", example: "Dad cooks in the kitchen.", exampleZh: "爸爸在厨房做饭。" },
          { en: "bathroom", ipa: "/ˈbɑːθruːm/", zh: "浴室", example: "There is a mirror in the bathroom.", exampleZh: "浴室里有一面镜子。" },
          { en: "fridge", ipa: "/frɪdʒ/", zh: "冰箱", example: "Juice is in the fridge.", exampleZh: "果汁在冰箱里。" },
          { en: "sofa", ipa: "/ˈsəʊfə/", zh: "沙发", example: "There is a sofa by the lamp.", exampleZh: "灯旁边有一张沙发。" },
          { en: "closet", ipa: "/ˈklɒzɪt/", zh: "衣柜", example: "Dresses are in the closet.", exampleZh: "裙子在衣柜里。" },
          { en: "plant", ipa: "/plɑːnt/", zh: "植物", example: "There is a plant by the window.", exampleZh: "窗边有一盆植物。" },
        ],
        grammar: {
          title: "there is / there are",
          titleZh: "表示“有”",
          pattern: "There is + 单数.  There are + 复数.",
          notes: [
            "说某处存在某物用 there is / there are，不是 has。",
            "问句：Is there a ...? Are there any ...?",
            "否定：There isn't ... / There aren't ...",
          ],
          examples: [
            { en: "There is a big bed in the bedroom.", zh: "卧室里有一张大床。" },
            { en: "There are two lamps in the living room.", zh: "客厅里有两盏灯。" },
            { en: "Is there a plant? — Yes, there is.", zh: "有植物吗？——有。" },
          ],
        },
        reading: {
          title: "A Home for Pip Too",
          titleZh: "皮普也有一个家",
          text: "Lily's family has a new home. There is a bedroom for Lily. There is a big bed, a closet and a plant by the window.\n\nThere is a living room with a sofa. There are two lamps and many books. The kitchen is small but bright. There is a fridge and a long table.\n\nPip wants a room too. Lily puts a little box near the plant. \"There is a soft cloth in it,\" she says. \"This is your bed.\"\n\nPip smiles. \"There is a home for me. Thank you.\"",
          textZh:
            "莉莉一家有了新家。莉莉有一间卧室。里面有一张大床、一个衣柜，窗边还有一盆植物。\n\n客厅里有沙发。有两盏灯和很多书。厨房虽小但很亮。有冰箱和一张长桌。\n\n皮普也想要一个房间。莉莉在植物旁放了一个小盒子。“里面有一块软布，”她说，“这是你的床。”\n\n皮普笑了：“我也有家了。谢谢。”",
        },
        practice: [
          { type: "choice", q: "There _____ a big bed in Lily's bedroom.", options: ["are", "is", "am"], answer: 1 },
          { type: "choice", q: "客厅里有两盏灯，应该说：", options: ["There is two lamps.", "There are two lamps.", "There have two lamps."], answer: 1 },
          { type: "fill", q: "_____ there a closet in the bedroom?", answer: "Is", hint: "单数问句开头" },
          { type: "order", words: ["is", "There", "a", "sofa", "."], answer: "There is a sofa." },
          { type: "tf", q: "Pip has a little bed near the plant.", answer: true },
          { type: "listen", audio: "There are two lamps in the living room.", options: ["There are two lamps in the living room.", "There is a fridge in the bedroom.", "There are two beds in the kitchen."], answer: 0 },
        ],
        fun: {
          title: "Room hunt",
          titleZh: "找房间",
          chant: [
            "Bedroom, kitchen, bathroom, hall,",
            "Living room — I like them all.",
            "There is a bed. There are two chairs.",
            "Open the door. Who is there?",
          ],
        },
      },

      {
        id: 6,
        title: "In a Nature Park",
        titleZh: "在自然公园",
        theme: "nature",
        color: "#3b8f4f",
        emoji: "🌿",
        goals: [
          "描述公园里的自然景物",
          "用 Is there / Are there 提问",
          "读一篇绿园一日的短文",
        ],
        dialogue: {
          title: "Green Park",
          titleZh: "绿园",
          scene: "Sunday. The children walk into Green Park with Ms. Green.",
          sceneZh: "星期天，孩子们和格林老师走进绿园。",
          lines: [
            { speaker: "Ms. Green", text: "Look! There is a forest and a river.", zh: "看！有一片森林和一条河。" },
            { speaker: "Tom", text: "Is there a lake?", zh: "有湖吗？" },
            { speaker: "Ms. Green", text: "Yes, there is. It's behind those flowers.", zh: "有。就在那些花的后面。" },
            { speaker: "Maya", text: "Are there any rabbits?", zh: "有兔子吗？" },
            { speaker: "Lily", text: "Yes! There are two rabbits near the bridge.", zh: "有！桥边有两只兔子。" },
            { speaker: "Ben", text: "I see a mountain far away. And so many birds!", zh: "我看见远处有一座山。还有好多鸟！" },
            { speaker: "Pip", text: "Is there a picnic table? I'm hungry.", zh: "有野餐桌吗？我饿了。" },
            { speaker: "Ms. Green", text: "There is one under the tree. Let's sit and look.", zh: "树下有一张。我们坐下看看吧。" },
          ],
        },
        vocab: [
          { en: "forest", ipa: "/ˈfɒrɪst/", zh: "森林", example: "There is a forest in the park.", exampleZh: "公园里有一片森林。" },
          { en: "river", ipa: "/ˈrɪvə(r)/", zh: "河", example: "The river is long and quiet.", exampleZh: "这条河又长又安静。" },
          { en: "lake", ipa: "/leɪk/", zh: "湖", example: "Is there a lake? Yes, there is.", exampleZh: "有湖吗？有。" },
          { en: "mountain", ipa: "/ˈmaʊntən/", zh: "山", example: "I see a mountain far away.", exampleZh: "我看见远处有一座山。" },
          { en: "flower", ipa: "/ˈflaʊə(r)/", zh: "花", example: "There are many flowers by the lake.", exampleZh: "湖边有很多花。" },
          { en: "rabbit", ipa: "/ˈræbɪt/", zh: "兔子", example: "There are two rabbits near the bridge.", exampleZh: "桥边有两只兔子。" },
          { en: "bird", ipa: "/bɜːd/", zh: "鸟", example: "Birds sing in the forest.", exampleZh: "鸟儿在森林里歌唱。" },
          { en: "bridge", ipa: "/brɪdʒ/", zh: "桥", example: "Let's walk over the bridge.", exampleZh: "我们走过这座桥吧。" },
        ],
        grammar: {
          title: "Is there ...? Are there ...?",
          titleZh: "询问某处是否有",
          pattern: "Is there a + 单数?  Are there any + 复数?",
          notes: [
            "单数用 Is there a lake? 复数用 Are there any rabbits?",
            "肯定：Yes, there is. / Yes, there are.",
            "否定：No, there isn't. / No, there aren't.",
          ],
          examples: [
            { en: "Is there a river? — Yes, there is.", zh: "有河吗？——有。" },
            { en: "Are there any flowers? — Yes, there are.", zh: "有花吗？——有。" },
            { en: "Is there a zoo? — No, there isn't.", zh: "有动物园吗？——没有。" },
          ],
        },
        reading: {
          title: "A Day in Green Park",
          titleZh: "绿园的一天",
          text: "Green Park is not far from school. There is a forest, a river and a quiet lake. There is a small bridge over the river.\n\nOn Sunday, Lily, Tom, Maya, Ben and Pip walk there with Ms. Green. There are flowers by the lake. There are birds in the trees. Maya sees two rabbits near the bridge.\n\n\"Is there a mountain?\" Ben asks. \"Yes,\" Ms. Green says. \"It's far, but we can see it.\"\n\nThey sit under a tree. There is a picnic table. They eat sandwiches and look at the water. Pip is quiet. \"I like this park,\" he says. \"There is room for a little fox.\"",
          textZh:
            "绿园离学校不远。那里有森林、河和安静的湖。河上有一座小桥。\n\n星期天，莉莉、汤姆、玛雅、本和皮普跟格林老师走去那里。湖边有花，树上有鸟。玛雅看见桥边有两只兔子。\n\n“有山吗？”本问。“有，”格林老师说，“它在远处，但我们能看见。”\n\n他们坐在树下。有一张野餐桌。他们吃三明治，看着水面。皮普很安静。“我喜欢这个公园，”他说，“这里有小狐狸的位置。”",
        },
        practice: [
          { type: "choice", q: "Are there any rabbits in Green Park?", options: ["Yes, there are two near the bridge.", "No, there is a zoo.", "Yes, there is a fridge."], answer: 0 },
          { type: "choice", q: "问“有花吗？”更合适的是：", options: ["Is there any flowers?", "Are there any flowers?", "Have there flowers?"], answer: 1 },
          { type: "fill", q: "_____ there a lake behind the flowers?", answer: "Is", hint: "单数" },
          { type: "order", words: ["there", "Are", "any", "birds", "?"], answer: "Are there any birds?" },
          { type: "tf", q: "There is a small bridge over the river.", answer: true },
          { type: "listen", audio: "There is a forest and a river.", options: ["There is a forest and a river.", "There is a kitchen and a sofa.", "There are two hamburgers."], answer: 0 },
        ],
        fun: {
          title: "Nature walk",
          titleZh: "自然散步",
          chant: [
            "Forest, river, lake and hill,",
            "Rabbits hop and birds sit still.",
            "Is there a bridge? Yes, there is!",
            "Nature park — what a day this is!",
          ],
        },
      },

      {
        id: 7,
        title: "My Day",
        titleZh: "我的一天",
        theme: "day",
        color: "#d4a017",
        emoji: "⏰",
        goals: [
          "用钟点说出作息",
          "问答：What time do you ...?",
          "读一篇老师的一天",
        ],
        dialogue: {
          title: "What Time?",
          titleZh: "几点？",
          scene: "Tuesday morning. Tom is almost late.",
          sceneZh: "星期二早上，汤姆差点迟到。",
          lines: [
            { speaker: "Ms. Green", text: "Good morning, Tom. What time do you get up?", zh: "早上好，汤姆。你几点起床？" },
            { speaker: "Tom", text: "I get up at seven o'clock. Today I got up at seven thirty!", zh: "我七点起床。今天我七点半才起！" },
            { speaker: "Lily", text: "I eat breakfast at seven fifteen. Then I go to school.", zh: "我七点十五分吃早餐，然后去上学。" },
            { speaker: "Maya", text: "We have class at eight. I like the quiet walk to school.", zh: "我们八点上课。我喜欢安静地走路上学。" },
            { speaker: "Ben", text: "I eat lunch at twelve. I play sports at three thirty.", zh: "我十二点吃午饭。三点半做运动。" },
            { speaker: "Tom", text: "I do homework at five. I go to bed at nine.", zh: "我五点写作业。九点睡觉。" },
            { speaker: "Pip", text: "I sleep at any time. That is my day!", zh: "我随时都能睡。那就是我的一天！" },
            { speaker: "Ms. Green", text: "A good day has a good clock. Try seven o'clock tomorrow, Tom.", zh: "好的一天要有好的时钟。汤姆，明天试着七点起。" },
          ],
        },
        vocab: [
          { en: "get up", ipa: "/ɡet ʌp/", zh: "起床", example: "I get up at seven o'clock.", exampleZh: "我七点起床。" },
          { en: "eat breakfast", ipa: "/iːt ˈbrekfəst/", zh: "吃早餐", example: "She eats breakfast at 7:15.", exampleZh: "她七点十五分吃早餐。" },
          { en: "go to school", ipa: "/ɡəʊ tə skuːl/", zh: "去上学", example: "We go to school after breakfast.", exampleZh: "我们吃完早餐去上学。" },
          { en: "have class", ipa: "/hæv klɑːs/", zh: "上课", example: "We have class at eight.", exampleZh: "我们八点上课。" },
          { en: "eat lunch", ipa: "/iːt lʌntʃ/", zh: "吃午饭", example: "I eat lunch at twelve.", exampleZh: "我十二点吃午饭。" },
          { en: "play sports", ipa: "/pleɪ spɔːts/", zh: "做运动", example: "Ben plays sports at 3:30.", exampleZh: "本三点半做运动。" },
          { en: "go to bed", ipa: "/ɡəʊ tə bed/", zh: "上床睡觉", example: "Tom goes to bed at nine.", exampleZh: "汤姆九点睡觉。" },
          { en: "o'clock", ipa: "/əˈklɒk/", zh: "整点", example: "It's seven o'clock.", exampleZh: "现在是七点整。" },
        ],
        grammar: {
          title: "What time do you ...?",
          titleZh: "询问时间习惯",
          pattern: "What time do you + 动词? — I + 动词 at + 时间.",
          notes: [
            "整点用 o'clock：seven o'clock。",
            "七点半可以说 seven thirty 或 half past seven。",
            "时间前用 at：at eight, at 3:30。",
          ],
          examples: [
            { en: "What time do you get up? — I get up at seven o'clock.", zh: "你几点起床？——我七点起床。" },
            { en: "What time does Ben play sports? — At three thirty.", zh: "本几点做运动？——三点半。" },
            { en: "We have class at eight.", zh: "我们八点上课。" },
          ],
        },
        reading: {
          title: "Ms. Green's Day",
          titleZh: "格林老师的一天",
          text: "Ms. Green gets up at six thirty. She eats breakfast at seven. She walks to school at seven twenty. The streets are quiet.\n\nShe has class at eight. At twelve she eats lunch with the children. At three thirty she plays sports with Class Five. At five she reads at her desk.\n\nShe goes home at six. She eats dinner and looks at the stars with her cat. She goes to bed at ten.\n\n\"A day is like a little story,\" she tells the class. \"Get up, try, rest, and begin again.\"",
          textZh:
            "格林老师六点半起床。她七点吃早餐。七点二十分走路去学校。街上很安静。\n\n她八点上课。十二点和孩子们一起吃午饭。三点半她和五班一起做运动。五点她在书桌前读书。\n\n她六点回家。她吃晚饭，再和猫一起看星星。她十点睡觉。\n\n“一天就像一个小故事，”她告诉全班，“起床，努力，休息，然后再开始。”",
        },
        practice: [
          { type: "choice", q: "What time does Ms. Green get up?", options: ["At seven o'clock.", "At six thirty.", "At eight o'clock."], answer: 1 },
          { type: "choice", q: "时间七点整，英语常说：", options: ["seven clock", "seven o'clock", "o'clock seven"], answer: 1 },
          { type: "fill", q: "I go to bed _____ nine.", answer: "at", hint: "时间前的介词" },
          { type: "order", words: ["time", "What", "you", "get", "up", "do", "?"], answer: "What time do you get up?" },
          { type: "tf", q: "Tom usually gets up at seven o'clock.", answer: true },
          { type: "listen", audio: "I eat lunch at twelve.", options: ["I eat lunch at twelve.", "I go to bed at twelve.", "I get up at twelve."], answer: 0 },
        ],
        fun: {
          title: "Clock chant",
          titleZh: "时钟儿歌",
          chant: [
            "Seven o'clock, I get up.",
            "Eight o'clock, cup by cup.",
            "Twelve o'clock, eat and play.",
            "Nine o'clock, end the day.",
          ],
        },
      },

      {
        id: 8,
        title: "My Favourite Season",
        titleZh: "我最喜欢的季节",
        theme: "season",
        color: "#4aa3a8",
        emoji: "🍂",
        goals: [
          "说出四季和天气",
          "问答：Which season do you like best? Why?",
          "用 because 说明原因",
        ],
        dialogue: {
          title: "Four Seasons",
          titleZh: "四季",
          scene: "Art class. The children paint seasons on big paper.",
          sceneZh: "美术课上，孩子们在大纸上画四季。",
          lines: [
            { speaker: "Ms. Green", text: "Which season do you like best, Maya?", zh: "玛雅，你最喜欢哪个季节？" },
            { speaker: "Maya", text: "I like spring best. It's warm. I can see flowers.", zh: "我最喜欢春天。天气暖和，我能看见花。" },
            { speaker: "Ben", text: "I like summer. It's hot. I can swim every day!", zh: "我喜欢夏天。天气热，我可以天天游泳！" },
            { speaker: "Lily", text: "I like autumn. It's cool. We pick apples.", zh: "我喜欢秋天。天气凉爽，我们摘苹果。" },
            { speaker: "Tom", text: "I like winter best because I can make a snowman.", zh: "我最喜欢冬天，因为我可以堆雪人。" },
            { speaker: "Pip", text: "I like autumn too. The leaves are like a red bed.", zh: "我也喜欢秋天。树叶像一张红床。" },
            { speaker: "Ms. Green", text: "Every season has a gift. Paint your favourite one.", zh: "每个季节都有礼物。画出你最喜欢的那个。" },
          ],
        },
        vocab: [
          { en: "spring", ipa: "/sprɪŋ/", zh: "春天", example: "Spring is warm. Flowers come out.", exampleZh: "春天暖和，花开了。" },
          { en: "summer", ipa: "/ˈsʌmə(r)/", zh: "夏天", example: "Summer is hot. We can swim.", exampleZh: "夏天很热，我们可以游泳。" },
          { en: "autumn", ipa: "/ˈɔːtəm/", zh: "秋天", example: "Autumn is cool. We pick apples.", exampleZh: "秋天凉爽，我们摘苹果。" },
          { en: "winter", ipa: "/ˈwɪntə(r)/", zh: "冬天", example: "Winter is cold. We make a snowman.", exampleZh: "冬天很冷，我们堆雪人。" },
          { en: "warm", ipa: "/wɔːm/", zh: "温暖的", example: "The sun is warm in spring.", exampleZh: "春天的太阳很温暖。" },
          { en: "cool", ipa: "/kuːl/", zh: "凉爽的", example: "Autumn days are cool.", exampleZh: "秋天的日子很凉爽。" },
          { en: "hot", ipa: "/hɒt/", zh: "炎热的", example: "Summer days are hot.", exampleZh: "夏天的日子很炎热。" },
          { en: "pick apples", ipa: "/pɪk ˈæplz/", zh: "摘苹果", example: "We pick apples in autumn.", exampleZh: "我们在秋天摘苹果。" },
          { en: "make a snowman", ipa: "/meɪk ə ˈsnəʊmæn/", zh: "堆雪人", example: "Tom makes a snowman in winter.", exampleZh: "汤姆冬天堆雪人。" },
        ],
        grammar: {
          title: "Which season do you like best?",
          titleZh: "询问最喜欢的季节",
          pattern: "Which season do you like best? — I like ... best because ...",
          notes: [
            "which 用来在几个选项里选择。",
            "because 后面接原因：because I can swim。",
            "天气形容词：warm / hot / cool / cold。",
          ],
          examples: [
            { en: "Which season do you like best? — I like summer best.", zh: "你最喜欢哪个季节？——我最喜欢夏天。" },
            { en: "Why? — Because I can swim.", zh: "为什么？——因为我可以游泳。" },
            { en: "I like winter best because I can make a snowman.", zh: "我最喜欢冬天，因为我可以堆雪人。" },
          ],
        },
        reading: {
          title: "Seasons in Our Town",
          titleZh: "我们小镇的四季",
          text: "Our town has four clear seasons. Spring is warm. There are flowers in Green Park. Maya likes spring because she can draw the colours.\n\nSummer is hot. Children swim and eat ice cream. Ben likes summer best.\n\nAutumn is cool. Families pick apples. The leaves are yellow and red. Pip sleeps on them.\n\nWinter is cold. Tom makes a snowman with a carrot nose. Sometimes there is no snow, but there is still hot tea and a quiet night.\n\nWhich season do you like best?",
          textZh:
            "我们的小镇有四个分明的季节。春天暖和。绿园里有花。玛雅喜欢春天，因为她能画出那些颜色。\n\n夏天很热。孩子们游泳、吃冰淇淋。本最喜欢夏天。\n\n秋天凉爽。家家户户摘苹果。树叶又黄又红。皮普睡在叶子上。\n\n冬天很冷。汤姆堆一个胡萝卜鼻子的雪人。有时没有雪，但仍然有热茶和一个安静的夜晚。\n\n你最喜欢哪个季节？",
        },
        practice: [
          { type: "choice", q: "Why does Tom like winter best?", options: ["Because he can swim.", "Because he can make a snowman.", "Because he can pick apples."], answer: 1 },
          { type: "choice", q: "because 用来：", options: ["问好天气", "说明原因", "点餐"], answer: 1 },
          { type: "fill", q: "I like autumn best _____ I can pick apples.", answer: "because", hint: "因为" },
          { type: "order", words: ["season", "Which", "you", "like", "do", "best", "?"], answer: "Which season do you like best?" },
          { type: "tf", q: "Spring is cold and we make a snowman.", answer: false },
          { type: "listen", audio: "I like summer best because I can swim.", options: ["I like summer best because I can swim.", "I like winter best because I can swim.", "I like spring best because I can cook."], answer: 0 },
        ],
        fun: {
          title: "Season wheel",
          titleZh: "四季转盘",
          chant: [
            "Spring is warm. Flowers grow.",
            "Summer is hot. Rivers flow.",
            "Autumn is cool. Apples fall.",
            "Winter is cold. Soft snow for all.",
          ],
        },
      },

      {
        id: 9,
        title: "When Is the Show?",
        titleZh: "演出在什么时候？",
        theme: "calendar",
        color: "#c23b5a",
        emoji: "🎉",
        goals: [
          "说出月份和日期",
          "问答：When is ...? It's on ...",
          "读学校活动日历",
        ],
        dialogue: {
          title: "School Calendar",
          titleZh: "学校日历",
          scene: "Ms. Green puts a big calendar on the wall.",
          sceneZh: "格林老师把一张大日历贴在墙上。",
          lines: [
            { speaker: "Lily", text: "When is the singing contest?", zh: "歌唱比赛是什么时候？" },
            { speaker: "Ms. Green", text: "It's in April. It's on the twelfth.", zh: "在四月。是十二号。" },
            { speaker: "Tom", text: "When is the sports meet?", zh: "运动会是什么时候？" },
            { speaker: "Ms. Green", text: "It's in May. It's on the fourth.", zh: "在五月。是四号。" },
            { speaker: "Maya", text: "When is the school trip?", zh: "学校旅行是什么时候？" },
            { speaker: "Ms. Green", text: "It's on June the first. That's Children's Day too!", zh: "在六月一日。那天也是儿童节！" },
            { speaker: "Ben", text: "When is your birthday, Pip?", zh: "皮普，你的生日是什么时候？" },
            { speaker: "Pip", text: "It's in October. It's on the tenth. Please come!", zh: "在十月。是十号。请来玩！" },
            { speaker: "Lily", text: "My birthday is in March. It's on the third.", zh: "我的生日在三月，是三号。" },
          ],
        },
        vocab: [
          { en: "January", ipa: "/ˈdʒænjuəri/", zh: "一月", example: "New Year is in January.", exampleZh: "新年在一月。" },
          { en: "March", ipa: "/mɑːtʃ/", zh: "三月", example: "Lily's birthday is in March.", exampleZh: "莉莉的生日在三月。" },
          { en: "April", ipa: "/ˈeɪprəl/", zh: "四月", example: "The singing contest is in April.", exampleZh: "歌唱比赛在四月。" },
          { en: "June", ipa: "/dʒuːn/", zh: "六月", example: "Children's Day is in June.", exampleZh: "儿童节在六月。" },
          { en: "October", ipa: "/ɒkˈtəʊbə(r)/", zh: "十月", example: "Pip's birthday is in October.", exampleZh: "皮普的生日在十月。" },
          { en: "sports meet", ipa: "/spɔːts miːt/", zh: "运动会", example: "The sports meet is on May 4th.", exampleZh: "运动会在五月四日。" },
          { en: "contest", ipa: "/ˈkɒntest/", zh: "比赛；竞赛", example: "When is the singing contest?", exampleZh: "歌唱比赛是什么时候？" },
          { en: "birthday", ipa: "/ˈbɜːθdeɪ/", zh: "生日", example: "When is your birthday?", exampleZh: "你的生日是哪天？" },
        ],
        grammar: {
          title: "When is ...?",
          titleZh: "询问日期",
          pattern: "When is + 活动? — It's in + 月份. / It's on + 日期.",
          notes: [
            "月份前用 in：in April。",
            "具体日期前用 on：on the twelfth, on June 1st。",
            "序数词：1st first, 2nd second, 3rd third, 4th fourth, 12th twelfth。",
          ],
          examples: [
            { en: "When is the sports meet? — It's in May. It's on the fourth.", zh: "运动会是什么时候？——在五月，四号。" },
            { en: "When is your birthday? — It's on March 3rd.", zh: "你的生日是哪天？——三月三日。" },
            { en: "Children's Day is on June 1st.", zh: "儿童节在六月一日。" },
          ],
        },
        reading: {
          title: "Our Busy Calendar",
          titleZh: "我们忙碌的日历",
          text: "This term is full of days to remember. The singing contest is in April. It is on the twelfth. Lily will sing.\n\nThe sports meet is in May. It is on the fourth. Tom and Ben will run.\n\nThe school trip is on June 1st. That is Children's Day. The class will go to Green Park. There is a forest, a lake and a picnic table.\n\nPip's birthday is in October. It is on the tenth. \"It's not this term,\" Pip says, \"but you can write it now. Friends remember.\"\n\nMs. Green writes every date in yellow. The wall looks like sunshine.",
          textZh:
            "这学期有许多要记住的日子。歌唱比赛在四月十二日。莉莉会唱歌。\n\n运动会在五月四日。汤姆和本会跑步。\n\n学校旅行在六月一日，也是儿童节。全班将去绿园。那里有森林、湖和野餐桌。\n\n皮普的生日在十月十日。“不是这学期，”皮普说，“但你们可以现在就写下来。朋友会记得。”\n\n格林老师用黄色写下每一个日期。那面墙看起来像阳光。",
        },
        practice: [
          { type: "choice", q: "When is the singing contest?", options: ["It's on April 12th.", "It's on May 4th.", "It's on June 1st."], answer: 0 },
          { type: "choice", q: "月份前常用：", options: ["on", "in", "at"], answer: 1 },
          { type: "fill", q: "Children's Day is _____ June 1st.", answer: "on", hint: "具体日期前" },
          { type: "order", words: ["is", "When", "your", "birthday", "?"], answer: "When is your birthday?" },
          { type: "tf", q: "The sports meet is in May.", answer: true },
          { type: "listen", audio: "It's on the twelfth of April.", options: ["It's on the twelfth of April.", "It's on the tenth of October.", "It's on the first of June."], answer: 0 },
        ],
        fun: {
          title: "Months march",
          titleZh: "十二月进行曲",
          chant: [
            "January, February, March, April, May,",
            "June and July, then August comes to play.",
            "September, October, November, then",
            "December waves — start the year again!",
          ],
        },
      },

      {
        id: 10,
        title: "Whose Dog Is It?",
        titleZh: "这是谁的狗？",
        theme: "pets",
        color: "#8b6914",
        emoji: "🐶",
        goals: [
          "用 whose 询问物品主人",
          "使用 mine, yours, his, hers, ours, theirs",
          "读一篇失物招领故事",
        ],
        dialogue: {
          title: "Lost and Found",
          titleZh: "失物招领",
          scene: "After PE. A small dog sits by the school gate.",
          sceneZh: "体育课后，一只小狗坐在学校门口。",
          lines: [
            { speaker: "Tom", text: "Look! A dog! Whose dog is it?", zh: "看！一只狗！这是谁的狗？" },
            { speaker: "Lily", text: "It isn't mine. My dog is at home.", zh: "不是我的。我的狗在家里。" },
            { speaker: "Ben", text: "Is it yours, Maya?", zh: "玛雅，是你的吗？" },
            { speaker: "Maya", text: "No, it isn't mine. Maybe it's his. Look at Mr. Brown!", zh: "不，不是我的。也许是他的。看布朗老师！" },
            { speaker: "Mr. Brown", text: "Oh! That's my dog, Cookie. Thank you!", zh: "哦！那是我的狗，曲奇。谢谢你们！" },
            { speaker: "Pip", text: "Whose bag is this? It's pink.", zh: "这是谁的包？它是粉红色的。" },
            { speaker: "Lily", text: "It's hers. It's Maya's bag.", zh: "是她的。是玛雅的包。" },
            { speaker: "Maya", text: "Yes, it's mine. I am so happy!", zh: "对，是我的。我好高兴！" },
          ],
        },
        vocab: [
          { en: "whose", ipa: "/huːz/", zh: "谁的", example: "Whose dog is it?", exampleZh: "这是谁的狗？" },
          { en: "mine", ipa: "/maɪn/", zh: "我的（名词性）", example: "It isn't mine.", exampleZh: "那不是我的。" },
          { en: "yours", ipa: "/jɔːz/", zh: "你的；你们的", example: "Is this yours?", exampleZh: "这是你的吗？" },
          { en: "his", ipa: "/hɪz/", zh: "他的", example: "The dog is his.", exampleZh: "这只狗是他的。" },
          { en: "hers", ipa: "/hɜːz/", zh: "她的", example: "The pink bag is hers.", exampleZh: "那个粉红包是她的。" },
          { en: "ours", ipa: "/aʊəz/", zh: "我们的", example: "This classroom is ours.", exampleZh: "这间教室是我们的。" },
          { en: "theirs", ipa: "/ðeəz/", zh: "他们的", example: "Those books are theirs.", exampleZh: "那些书是他们的。" },
          { en: "cute", ipa: "/kjuːt/", zh: "可爱的", example: "Cookie is a cute dog.", exampleZh: "曲奇是一只可爱的狗。" },
        ],
        grammar: {
          title: "Whose ... is it?",
          titleZh: "询问所属",
          pattern: "Whose + 物品 + is it? — It's mine / yours / his / hers.",
          notes: [
            "whose 问主人；who's = who is，意思不同。",
            "mine 后面不再加名词：It's mine. 不是 It's mine bag.",
            "my / your / her 后面要加名词：It's my bag.",
          ],
          examples: [
            { en: "Whose dog is it? — It's his. It's Mr. Brown's dog.", zh: "这是谁的狗？——是他的。是布朗老师的狗。" },
            { en: "Is this yours? — No, it isn't mine. It's hers.", zh: "这是你的吗？——不，不是我的。是她的。" },
            { en: "These books are ours.", zh: "这些书是我们的。" },
          ],
        },
        reading: {
          title: "Cookie Comes to School",
          titleZh: "曲奇来到学校",
          text: "A cute dog sits by the gate. \"Whose dog is it?\" Tom asks. It isn't Lily's. It isn't Maya's. It isn't Ben's.\n\nMr. Brown runs over. \"Cookie! You're here!\" The dog is his. Cookie is quiet with children and noisy with birds.\n\nThen Pip finds a pink bag. \"Whose bag is this?\" \"It's mine,\" Maya says. \"Thank you, Pip.\"\n\nMs. Green puts a box in the hall. The sign says Lost and Found. \"If it isn't yours, put it here. If it is yours, take it home.\"\n\nCookie wags his tail. School can be a home for a morning.",
          textZh:
            "一只可爱的狗坐在门口。“这是谁的狗？”汤姆问。不是莉莉的，不是玛雅的，也不是本的。\n\n布朗老师跑过来：“曲奇！你在这儿！”这只狗是他的。曲奇和孩子们在一起很安静，对鸟却很吵。\n\n接着皮普发现一个粉红包。“这是谁的包？”“是我的，”玛雅说，“谢谢你，皮普。”\n\n格林老师在大厅放了一个盒子，牌子上写着“失物招领”。“如果不是你的，放在这里。如果是你的，带回家。”\n\n曲奇摇着尾巴。学校也可以成为一个上午的家。",
        },
        practice: [
          { type: "choice", q: "Whose dog is Cookie?", options: ["It's Maya's.", "It's Mr. Brown's.", "It's Pip's."], answer: 1 },
          { type: "choice", q: "It's mine. 中的 mine 意思是：", options: ["我（主语）", "我的（东西）", "我在"], answer: 1 },
          { type: "fill", q: "_____ bag is this? It's Maya's.", answer: "Whose", hint: "谁的" },
          { type: "order", words: ["dog", "Whose", "is", "it", "?"], answer: "Whose dog is it?" },
          { type: "tf", q: "The pink bag is Maya's.", answer: true },
          { type: "listen", audio: "It isn't mine. It's hers.", options: ["It isn't mine. It's hers.", "It isn't his. It's ours.", "It isn't yours. It's theirs."], answer: 0 },
        ],
        fun: {
          title: "Mine or yours?",
          titleZh: "我的还是你的？",
          chant: [
            "Mine, yours, his and hers,",
            "Ours, theirs — the word that fits.",
            "Whose book? Whose shoe? Whose cute little dog?",
            "Ask with whose, not who's. Don't mix the pair!",
          ],
        },
      },

      {
        id: 11,
        title: "Work Quietly!",
        titleZh: "安静地做！",
        theme: "rules",
        color: "#3d6b8a",
        emoji: "📚",
        goals: [
          "听懂并使用课堂指令",
          "用副词 quietly / carefully 等",
          "读图书馆规则",
        ],
        dialogue: {
          title: "In the Library",
          titleZh: "在图书馆",
          scene: "The class walks into the school library.",
          sceneZh: "全班走进学校图书馆。",
          lines: [
            { speaker: "Ms. Green", text: "Please walk in quietly. This is a quiet place.", zh: "请安静地走进来。这是安静的地方。" },
            { speaker: "Tom", text: "Can we talk?", zh: "我们可以说话吗？" },
            { speaker: "Ms. Green", text: "Talk quietly, please. Don't talk loudly.", zh: "请小声说。不要大声说话。" },
            { speaker: "Lily", text: "Look at the old books. I'll take them carefully.", zh: "看这些旧书。我会小心拿。" },
            { speaker: "Ben", text: "Can I eat my sandwich here?", zh: "我可以在这里吃三明治吗？" },
            { speaker: "Ms. Green", text: "No eating, please. Eat outside.", zh: "请不要吃东西。到外面吃。" },
            { speaker: "Maya", text: "Let's take turns with the big picture book.", zh: "这本大图画书我们轮流看吧。" },
            { speaker: "Pip", text: "I'll keep to the desk. I won't jump.", zh: "我会待在书桌边。我不会跳。" },
            { speaker: "Ms. Green", text: "Good. Work quietly. Read happily.", zh: "很好。安静地做。开心地读。" },
          ],
        },
        vocab: [
          { en: "quietly", ipa: "/ˈkwaɪətli/", zh: "安静地", example: "Please walk in quietly.", exampleZh: "请安静地走进来。" },
          { en: "carefully", ipa: "/ˈkeəfəli/", zh: "小心地", example: "Take the old books carefully.", exampleZh: "小心拿这些旧书。" },
          { en: "loudly", ipa: "/ˈlaʊdli/", zh: "大声地", example: "Don't talk loudly in the library.", exampleZh: "不要在图书馆大声说话。" },
          { en: "quickly", ipa: "/ˈkwɪkli/", zh: "迅速地", example: "Line up quickly, please.", exampleZh: "请迅速排队。" },
          { en: "take turns", ipa: "/teɪk tɜːnz/", zh: "轮流", example: "Take turns with the picture book.", exampleZh: "轮流看这本图画书。" },
          { en: "keep to the desk", ipa: "/kiːp tə ðə desk/", zh: "待在座位上", example: "Keep to your desk, please.", exampleZh: "请待在自己的座位上。" },
          { en: "Don't", ipa: "/dəʊnt/", zh: "不要", example: "Don't eat in the library.", exampleZh: "不要在图书馆吃东西。" },
          { en: "please", ipa: "/pliːz/", zh: "请", example: "Work quietly, please.", exampleZh: "请安静地做。" },
        ],
        grammar: {
          title: "Work quietly!",
          titleZh: "祈使句 + 副词",
          pattern: "动词原形 (+ 副词)!   Don't + 动词原形!",
          notes: [
            "祈使句直接用动词原形：Walk. Read. Work.",
            "副词常放在动词后：work quietly, talk loudly。",
            "否定加 Don't：Don't eat. Don't jump.",
          ],
          examples: [
            { en: "Work quietly, please.", zh: "请安静地做。" },
            { en: "Take the books carefully.", zh: "小心拿这些书。" },
            { en: "Don't talk loudly. Don't eat here.", zh: "不要大声说话。不要在这里吃东西。" },
          ],
        },
        reading: {
          title: "Library Rules",
          titleZh: "图书馆规则",
          text: "Our library is a quiet garden of books. Please walk in quietly. Talk quietly. Don't talk loudly.\n\nTake the books carefully. Some books are old and soft. Take turns with the big picture books. Keep to your desk when you write.\n\nDon't eat in the library. Don't run. Line up quickly when the bell rings.\n\nPip wants to jump. He looks at the sign and sits. \"I can work quietly,\" he whispers. Ms. Green gives him a sticker that says Good Listener.\n\nRules help us share a quiet place.",
          textZh:
            "我们的图书馆是一座安静的书的花园。请安静地走进来。小声说话。不要大声说话。\n\n小心拿书。有些书又旧又软。大图画书要轮流看。写字时请待在座位上。\n\n不要在图书馆吃东西。不要跑。铃响时请迅速排队。\n\n皮普想跳。他看了看告示，坐下了。“我能安静地做，”他小声说。格林老师给他一枚贴纸，上面写着“好听众”。\n\n规则帮助我们分享一个安静的地方。",
        },
        practice: [
          { type: "choice", q: "In the library we should:", options: ["Talk loudly and eat.", "Walk in quietly and take turns.", "Run and jump."], answer: 1 },
          { type: "choice", q: "Don't eat. 是：", options: ["疑问句", "否定祈使句", "过去时"], answer: 1 },
          { type: "fill", q: "Please work _____ in the library.", answer: "quietly", hint: "安静地" },
          { type: "order", words: ["talk", "Don't", "loudly", "."], answer: "Don't talk loudly." },
          { type: "tf", q: "Pip gets a sticker that says Good Listener.", answer: true },
          { type: "listen", audio: "Take the books carefully, please.", options: ["Take the books carefully, please.", "Eat the books quickly, please.", "Throw the books loudly, please."], answer: 0 },
        ],
        fun: {
          title: "Quiet feet",
          titleZh: "轻轻的脚",
          chant: [
            "Walk quietly. Talk quietly.",
            "Read happily. Write carefully.",
            "Don't run. Don't shout.",
            "A quiet room lets stories out.",
          ],
        },
      },

      {
        id: 12,
        title: "A Letter to a Friend",
        titleZh: "给朋友的一封信",
        theme: "review",
        color: "#2c6e6a",
        emoji: "✉️",
        goals: [
          "复习本册主要句型",
          "读一封完整的英文短信",
          "写三到五句介绍自己的话",
        ],
        dialogue: {
          title: "We Remember",
          titleZh: "我们记得",
          scene: "The last English class of the book. Sunshine on the desks.",
          sceneZh: "这本书的最后一节英语课。阳光照在课桌上。",
          lines: [
            { speaker: "Ms. Green", text: "What can you do now, Class Five?", zh: "五班的同学们，现在你们会做什么？" },
            { speaker: "Lily", text: "I can say what people are like. Ms. Green is kind!", zh: "我能说出别人是什么样的人。格林老师很亲切！" },
            { speaker: "Tom", text: "I can talk about my week and my day.", zh: "我能谈论我的一周和我的一天。" },
            { speaker: "Maya", text: "I'd like to write a letter. I can do it.", zh: "我想写一封信。我能做到。" },
            { speaker: "Ben", text: "There is a park. There are friends. Whose book is this? It's ours!", zh: "有一个公园。有朋友。这是谁的书？是我们的！" },
            { speaker: "Pip", text: "Work quietly. Then play happily. That's the rule.", zh: "先安静地做，再开心地玩。这就是规则。" },
            { speaker: "Ms. Green", text: "Wonderful. Now read Maya's letter. Then write your own.", zh: "太好了。现在读玛雅的信，然后写下你们自己的。" },
          ],
        },
        vocab: [
          { en: "letter", ipa: "/ˈletə(r)/", zh: "信", example: "Maya writes a letter to a friend.", exampleZh: "玛雅给朋友写一封信。" },
          { en: "friend", ipa: "/frend/", zh: "朋友", example: "A friend is kind and helpful.", exampleZh: "朋友善良又乐于助人。" },
          { en: "remember", ipa: "/rɪˈmembə(r)/", zh: "记得", example: "I remember my first English class.", exampleZh: "我记得我的第一节英语课。" },
          { en: "favourite", ipa: "/ˈfeɪvərɪt/", zh: "最喜欢的", example: "Autumn is my favourite season.", exampleZh: "秋天是我最喜欢的季节。" },
          { en: "because", ipa: "/bɪˈkɒz/", zh: "因为", example: "I like winter because I can make a snowman.", exampleZh: "我喜欢冬天，因为我可以堆雪人。" },
          { en: "please", ipa: "/pliːz/", zh: "请", example: "Write back, please.", exampleZh: "请回信。" },
          { en: "happy", ipa: "/ˈhæpi/", zh: "快乐的", example: "I am happy at school.", exampleZh: "我在学校很快乐。" },
          { en: "write", ipa: "/raɪt/", zh: "写", example: "I can write a short letter.", exampleZh: "我能写一封短信。" },
        ],
        grammar: {
          title: "Year-end patterns",
          titleZh: "全年句型总复习",
          pattern: "把本册句型放进一封信里。",
          notes: [
            "What's she like? / What do you do on Mondays?",
            "I'd like ... / I can ... / There is ...",
            "What time ...? / Which season ...? / When is ...? / Whose ...? / Work quietly!",
          ],
          examples: [
            { en: "I am hard-working and I can speak English.", zh: "我很勤奋，而且我会说英语。" },
            { en: "There is a lake in our park. I like autumn best.", zh: "我们公园里有一个湖。我最喜欢秋天。" },
            { en: "Please write back soon.", zh: "请尽快回信。" },
          ],
        },
        reading: {
          title: "Maya's Letter",
          titleZh: "玛雅的信",
          text: "Dear Sam,\n\nMy name is Maya. I am ten. I am a little shy, but I am kind and hard-working.\n\nOn Mondays I have English. I get up at seven o'clock. I'd like juice and a sandwich for breakfast.\n\nI can draw cartoons. I can't do kung fu. There is a plant in my bedroom. There is a lake in Green Park.\n\nI like autumn best because I can pick apples. My birthday is in November. It's on the second.\n\nWhose fox is in our class? He is ours. His name is Pip. Work quietly, then play happily. That is our rule.\n\nPlease write back. Tell me what you are like.\n\nYour friend,\nMaya",
          textZh:
            "亲爱的山姆：\n\n我叫玛雅。我十岁。我有一点害羞，但我善良又勤奋。\n\n星期一我有英语课。我七点起床。早餐我想要果汁和三明治。\n\n我会画漫画。我不会功夫。我的卧室里有一盆植物。绿园里有一个湖。\n\n我最喜欢秋天，因为我可以摘苹果。我的生日在十一月二日。\n\n我们班的狐狸是谁的？是我们的。他叫皮普。先安静地做，再开心地玩。这是我们的规则。\n\n请回信。告诉我你是什么样的人。\n\n你的朋友\n玛雅",
        },
        practice: [
          { type: "choice", q: "What is Maya like?", options: ["She is shy, kind and hard-working.", "She is strict and old.", "She is noisy and tall."], answer: 0 },
          { type: "choice", q: "Which season does Maya like best?", options: ["Summer", "Autumn", "Winter"], answer: 1 },
          { type: "fill", q: "Maya gets up _____ seven o'clock.", answer: "at", hint: "时间前" },
          { type: "order", words: ["is", "My", "Maya", "name", "."], answer: "My name is Maya." },
          { type: "tf", q: "Pip is the class fox. He is theirs? No — Maya says he is ours.", answer: true },
          { type: "listen", audio: "Please write back. Tell me what you are like.", options: ["Please write back. Tell me what you are like.", "Please sit down. Tell me what you can cook.", "Please run quickly. Tell me whose dog it is."], answer: 0 },
        ],
        fun: {
          title: "Write your letter",
          titleZh: "写下你的信",
          chant: [
            "My name is ____. I am ten.",
            "I am kind. I can try again.",
            "I'd like a friend. I'd like a day",
            "with books, a park, and time to play.",
            "Please write back. I will wait.",
            "Sunshine English — Grade Five. That's great!",
          ],
        },
      },
    ],
  };
});
